"""Native-model comparison with Shah et al., Phys. Rev. B 88, 075411 (2013).

The physical structure in the paper is an Au--CdSe--Au dimer, but the paper's
semiclassical equations replace the whole metal antenna by one fitted bright
plasmon oscillator.  This module answers a different and useful question:
what does the *current project model* predict for the two stated Au spheroids?

Each spheroid keeps the project's quasistatic Johnson--Christy ellipsoid
polarizability and its passive Lorentz-mode realization.  In the perfectly
symmetric longitudinal geometry used by Shah, the two induced dipoles are
equal.  The explicit two-particle problem therefore reduces exactly (within
the project's point-dipole approximation) to one set of modal coordinates:

    F = E + J*mu_QD + K*mu_MNP,
    mu_MNP = C*(alpha_inf*F + sum(q_k)),
    E_QD = l_QD*(E + 2*J*mu_MNP).

Here J couples the QD to either MNP and K couples the two MNPs.  The total
observable dipole is 2*mu_MNP + mu_QD.  No change is made to
``qd_mnp_rational_fit.py``; this file is a geometry adapter around its material,
unit, pulse, density-matrix and passive-modal APIs.

The corrected semiclassical rates printed in the paper are not a completely
positive two-level generator: Gamma2=1.265 meV is smaller than
gamma1_eff/2~=1.508 meV.  Production calculations therefore expose two honest
profiles only: ``naive`` (free-QD gamma1) and ``purcell_cp`` (the article's
Purcell population rate plus its thermal pure dephasing).  The latter is the
default and has Gamma2=gamma_thermal+gamma1_eff/2.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

import matplotlib.pyplot as plt
import numpy as np
from scipy.constants import c as C_SI, epsilon_0
from scipy.integrate import solve_ivp
from scipy.optimize import brentq
from scipy.signal import find_peaks

from qd_mnp_linear_spectrum import (
    qd_linear_polarizability_au,
    quasistatic_work_loss_cross_section_cm2,
)
from qd_mnp_params import make_params_with_overrides
from qd_mnp_rational_fit import (
    AU_DIPOLE_C_M,
    AU_TIME_S,
    DEBYE_C_M,
    GaussianPulse,
    HybridQDPlasmonModel,
    HybridSystemParams,
    RationalLorentzFit,
    au_to_eV,
    au_to_fs,
    eV_to_au,
    field_au_to_si,
    field_si_to_au,
    fs_to_au,
    nm_to_au,
    params_to_physical_dict,
)


DecayProfile = Literal["naive", "purcell_cp"]
MNPResponse = Literal["modal", "material"]


# The N=10 values below were generated by HybridQDPlasmonModel for the Shah
# single-spheroid geometry on 0.8--3.0 eV.  They are a deterministic cache, not
# an independent material model.  ``--refit`` regenerates them through the
# current fitter.  The cache makes tests and ordinary comparison runs fast.
_SHAH_N10_ALPHA_INF = -0.6381545421433383
_SHAH_N10_STRENGTHS_AU2 = np.asarray(
    [
        0.0018102956167731442,
        0.004178866313061936,
        0.003225734529746785,
        0.0018310282967927516,
        0.0008822329686497569,
        0.001164074898989508,
        0.00204623826650739,
        0.002394451025924276,
        0.0023660998293926383,
        0.09133860268761826,
    ],
    dtype=float,
)
_SHAH_N10_OMEGA_EV = np.asarray(
    [
        2.096687389183518,
        2.151041959787527,
        2.2091662503082836,
        2.2961097515141082,
        2.4214865429362216,
        2.5610747044257782,
        2.727269410155186,
        2.918824099674621,
        3.0917796461718603,
        5.30992956249938,
    ],
    dtype=float,
)
_SHAH_N10_GAMMA_EV = np.asarray(
    [
        0.11626291484303466,
        0.10019564486291418,
        0.11420708571821549,
        0.1534442112473007,
        0.20290012685080444,
        0.2631413010792432,
        0.3269009492813064,
        0.3276373744124233,
        0.17143481684580444,
        0.008000000000000021,
    ],
    dtype=float,
)
_SHAH_N10_FIT_METRICS = {
    "normalized_rms_alpha": 0.022928052019936383,
    "normalized_rms_inv_alpha": 0.020617894828648675,
    "max_normalized_alpha_error": 0.05008459578369981,
}


@dataclass(frozen=True)
class Shah2013Profile:
    """Parameters explicitly stated in the paper and its Supplement."""

    mnp_semimajor_nm: float = 15.0
    mnp_semiminor_nm: float = 10.0
    mnp_surface_gap_nm: float = 6.0
    qd_radius_nm: float = 2.0
    eps_environment: float = 2.25
    eps_qd_infinity: float = 5.8
    transition_energy_ev: float = 2.042
    qd_dipole_debye: float = 13.91
    effective_dimer_dipole_debye: float = 2994.0
    plasmon_linewidth_mev: float = 150.2
    coupling_g_mev: float = 10.841
    qd_thermal_dephasing_mev: float = 1.265
    qd_free_population_decay_mev: float = 0.000268
    pulse_fwhm_intensity_fs: float = 20.0
    cw_intensities_w_cm2: tuple[float, ...] = (
        1.0e3,
        1.0e4,
        1.0e5,
        1.0e6,
    )
    pulse_fluences_j_cm2: tuple[float, ...] = (
        5.0e-9,
        5.0e-8,
        5.0e-7,
        5.0e-6,
    )

    def __post_init__(self) -> None:
        values = np.asarray(
            [
                self.mnp_semimajor_nm,
                self.mnp_semiminor_nm,
                self.mnp_surface_gap_nm,
                self.qd_radius_nm,
                self.eps_environment,
                self.eps_qd_infinity,
                self.transition_energy_ev,
                self.qd_dipole_debye,
                self.effective_dimer_dipole_debye,
                self.plasmon_linewidth_mev,
                self.coupling_g_mev,
                self.qd_thermal_dephasing_mev,
                self.qd_free_population_decay_mev,
                self.pulse_fwhm_intensity_fs,
            ],
            dtype=float,
        )
        if np.any(~np.isfinite(values)) or np.any(values <= 0.0):
            raise ValueError("All Shah profile constants must be finite and positive.")
        if self.mnp_semimajor_nm < self.mnp_semiminor_nm:
            raise ValueError("The Shah Au particles are prolate: semimajor >= semiminor.")
        if self.qd_mnp_surface_gap_nm <= 0.0:
            raise ValueError(
                "The centered QD must have a strictly positive surface gap "
                "to both MNPs."
            )
        if any(value <= 0.0 for value in self.cw_intensities_w_cm2):
            raise ValueError("CW intensities must be positive.")
        if any(value <= 0.0 for value in self.pulse_fluences_j_cm2):
            raise ValueError("Pulse fluences must be positive.")

    @property
    def mnp_center_distance_nm(self) -> float:
        return 2.0 * self.mnp_semimajor_nm + self.mnp_surface_gap_nm

    @property
    def qd_to_mnp_center_nm(self) -> float:
        return 0.5 * self.mnp_center_distance_nm

    @property
    def qd_mnp_surface_gap_nm(self) -> float:
        return (
            self.qd_to_mnp_center_nm
            - self.mnp_semimajor_nm
            - self.qd_radius_nm
        )

    @property
    def effective_population_decay_mev(self) -> float:
        g = self.coupling_g_mev
        gamma_s = self.plasmon_linewidth_mev
        gamma_1 = self.qd_free_population_decay_mev
        gamma_2 = self.qd_thermal_dephasing_mev
        return float(
            gamma_1
            + 4.0 * g**2
            / (4.0 * g**2 / gamma_s + gamma_1 + 2.0 * gamma_2 + gamma_s)
        )

    def rates_mev(self, decay_profile: DecayProfile) -> tuple[float, float]:
        """Return population gamma1 and total coherence Gamma2."""

        if decay_profile == "naive":
            gamma_1 = self.qd_free_population_decay_mev
            gamma_2_total = self.qd_thermal_dephasing_mev + 0.5 * gamma_1
        elif decay_profile == "purcell_cp":
            gamma_1 = self.effective_population_decay_mev
            gamma_2_total = self.qd_thermal_dephasing_mev + 0.5 * gamma_1
        else:
            raise ValueError("decay_profile must be 'naive' or 'purcell_cp'.")
        return float(gamma_1), float(gamma_2_total)


@dataclass(frozen=True)
class StabilityAudit:
    symmetric_poles_au: np.ndarray
    antisymmetric_poles_au: np.ndarray
    symmetric_stable: bool
    antisymmetric_stable: bool
    tolerance_au: float


@dataclass(frozen=True)
class HarmonicState:
    energy_ev: float
    intensity_w_cm2: float
    inversion: float
    excited_population: float
    qd_bloch_p_amplitude: complex
    qd_bloch_q_amplitude: complex
    qd_dipole_au: complex
    each_mnp_dipole_au: complex
    total_dipole_au: complex
    effective_alpha_au: complex
    paper_work_loss_cm2: float
    root_count: int
    max_periodic_bloch_radius: float


@dataclass(frozen=True)
class PulseTrace:
    fluence_j_cm2: float
    t_au: np.ndarray
    y: np.ndarray
    field_au: np.ndarray
    each_mnp_dipole_au: np.ndarray
    qd_dipole_au: np.ndarray
    total_dipole_au: np.ndarray
    max_bloch_radius: float
    min_density_eigenvalue: float
    tail_ratio: float
    solver_nfev: int
    max_step_au: float


@dataclass(frozen=True)
class PulseEnvelopeTrace:
    """Slow complex amplitudes in a frame rotating at the pulse carrier."""

    fluence_j_cm2: float
    carrier_omega_au: float
    t_au: np.ndarray
    state: np.ndarray
    field_envelope_au: np.ndarray
    each_mnp_envelope_au: np.ndarray
    qd_envelope_au: np.ndarray
    total_envelope_au: np.ndarray
    inversion: np.ndarray
    max_bloch_radius: float
    min_density_eigenvalue: float
    tail_ratio: float
    solver_nfev: int


def _longitudinal_depolarization_factor(c_au: float, a_au: float) -> float:
    eccentricity_squared = float(1.0 - (a_au / c_au) ** 2)
    if eccentricity_squared <= 0.0:
        return 1.0 / 3.0
    eccentricity = float(np.sqrt(eccentricity_squared))
    return float(
        (1.0 - eccentricity_squared)
        * (np.arctanh(eccentricity) - eccentricity)
        / eccentricity**3
    )


def _alpha_model(
    energies_ev: float | np.ndarray,
    fit: RationalLorentzFit,
) -> np.ndarray:
    omega = np.asarray(eV_to_au(energies_ev), dtype=float)
    alpha = np.full_like(omega, fit.alpha_inf, dtype=complex)
    for strength, mode_omega, mode_gamma in zip(
        fit.strengths_au2,
        fit.omega_modes_au,
        fit.gamma_modes_au,
    ):
        alpha += strength / (
            mode_omega**2 - omega**2 - 1j * mode_gamma * omega
        )
    return alpha


def _single_particle_material_alpha_dimless(
    params: HybridSystemParams,
    energies_ev: float | np.ndarray,
) -> np.ndarray:
    depolarization = _longitudinal_depolarization_factor(
        params.c_au,
        params.a_au,
    )
    epsilon = params.material.epsilon_at(energies_ev)
    contrast = epsilon - params.eps_m
    return np.asarray(
        contrast / (params.eps_m + depolarization * contrast),
        dtype=complex,
    )


def _cached_shah_fit(params: HybridSystemParams) -> RationalLorentzFit:
    mask = (
        (params.material.energy_eV >= 0.8)
        & (params.material.energy_eV <= 3.0)
    )
    energies = params.material.energy_eV[mask]
    target = _single_particle_material_alpha_dimless(params, energies)
    return RationalLorentzFit(
        alpha_inf=_SHAH_N10_ALPHA_INF,
        strengths_au2=_SHAH_N10_STRENGTHS_AU2,
        omega_modes_au=np.asarray(eV_to_au(_SHAH_N10_OMEGA_EV), dtype=float),
        gamma_modes_au=np.asarray(eV_to_au(_SHAH_N10_GAMMA_EV), dtype=float),
        energies_used_eV=energies,
        alpha_used=target,
        rms_alpha=0.0,
        rms_inv_alpha=0.0,
        cost=0.0,
        normalized_rms_alpha=_SHAH_N10_FIT_METRICS["normalized_rms_alpha"],
        normalized_rms_inv_alpha=_SHAH_N10_FIT_METRICS[
            "normalized_rms_inv_alpha"
        ],
        max_normalized_alpha_error=_SHAH_N10_FIT_METRICS[
            "max_normalized_alpha_error"
        ],
        min_imag_alpha_fit_window=0.0,
        passivity_grid_points=20001,
        passive_on_fit_window=True,
        passive_for_all_positive_frequencies=True,
    )


def build_shah_params(
    profile: Shah2013Profile,
    decay_profile: DecayProfile,
) -> HybridSystemParams:
    gamma_1_mev, gamma_2_mev = profile.rates_mev(decay_profile)
    return make_params_with_overrides(
        c_nm=profile.mnp_semimajor_nm,
        a_nm=profile.mnp_semiminor_nm,
        r_nm=profile.qd_to_mnp_center_nm,
        qd_radius_nm=profile.qd_radius_nm,
        eps_m=profile.eps_environment,
        eps_qd=profile.eps_qd_infinity,
        d_debye=profile.qd_dipole_debye,
        omega0_ev=profile.transition_energy_ev,
        gamma_population_mev=gamma_1_mev,
        gamma2_coherence_mev=gamma_2_mev,
        orientation="long",
        qd_dipole_convention="effective_external",
    )


class SymmetricDimerQDPlasmonModel:
    """Two identical native MNPs reduced to their symmetric bright sector."""

    fit_window_ev = (0.8, 3.0)

    def __init__(
        self,
        params: HybridSystemParams,
        fit: RationalLorentzFit,
        *,
        mnp_center_distance_nm: float,
        fit_provenance: str,
    ) -> None:
        self.params = params
        self.fit = fit
        self.n_modes = int(fit.strengths_au2.size)
        if params.G != 2.0:
            raise ValueError(
                "The Shah adapter is longitudinal and requires the fixed "
                "quasistatic factor G=2."
            )
        if params.axial_surface_gap_au <= 0.0:
            raise ValueError("The QD--MNP surface gap must be positive.")
        if params.Gamma_au < 0.5 * params.gamma_au:
            raise ValueError("Physical rates require Gamma2 >= gamma1/2.")
        self.C = float(params.eps_m * params.a_au**2 * params.c_au / 3.0)
        self.J = float(2.0 / (params.eps_m * params.R_au**3))
        self.mnp_center_distance_au = float(nm_to_au(mnp_center_distance_nm))
        if self.mnp_center_distance_au <= 2.0 * params.c_au:
            raise ValueError("The two MNP surfaces must have a positive gap.")
        if not np.isclose(
            self.mnp_center_distance_au,
            2.0 * params.R_au,
            rtol=1e-12,
            atol=0.0,
        ):
            raise ValueError(
                "Symmetric reduction requires the QD at the dimer center: "
                "D=2R."
            )
        self.K = float(
            2.0 / (params.eps_m * self.mnp_center_distance_au**3)
        )
        self.fit_provenance = fit_provenance
        instantaneous_denominator = 1.0 - self.K * self.C * fit.alpha_inf
        antisymmetric_denominator = 1.0 + self.K * self.C * fit.alpha_inf
        if min(abs(instantaneous_denominator), abs(antisymmetric_denominator)) < 1e-8:
            raise RuntimeError("The dimer instantaneous response is singular.")
        self._symmetric_instantaneous_denominator = float(
            instantaneous_denominator
        )
        self._antisymmetric_instantaneous_denominator = float(
            antisymmetric_denominator
        )
        self.stability = self._stability_audit()
        if not (
            self.stability.symmetric_stable
            and self.stability.antisymmetric_stable
        ):
            raise RuntimeError(
                "The native dimer has an unstable symmetric or antisymmetric "
                "field-free branch."
            )

    def alpha_single_dimless(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> np.ndarray:
        energies = np.asarray(energies_ev, dtype=float)
        if np.any(energies < self.fit_window_ev[0]) or np.any(
            energies > self.fit_window_ev[1]
        ):
            raise ValueError("Requested energy is outside the modal fit window.")
        if response == "modal":
            return _alpha_model(energies, self.fit)
        if response == "material":
            return _single_particle_material_alpha_dimless(self.params, energies)
        raise ValueError("response must be 'modal' or 'material'.")

    def alpha_each_mnp_au(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> np.ndarray:
        """Each-particle response after mutual MNP--MNP dressing."""

        alpha_single = self.C * self.alpha_single_dimless(
            energies_ev,
            response=response,
        )
        return alpha_single / (1.0 - self.K * alpha_single)

    def alpha_bare_dimer_au(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> np.ndarray:
        return 2.0 * self.alpha_each_mnp_au(
            energies_ev,
            response=response,
        )

    def linear_coupled_alpha_au(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        energies = np.asarray(energies_ev, dtype=float)
        omega = np.asarray(eV_to_au(energies), dtype=float)
        alpha_dimer = self.alpha_bare_dimer_au(energies, response=response)
        beta_qd = qd_linear_polarizability_au(
            omega,
            self.params.d_au,
            self.params.omega0_au,
            self.params.Gamma_au,
            self.params.qd_local_field_factor,
        )
        denominator = 1.0 - self.J**2 * alpha_dimer * beta_qd
        mu_dimer_over_e = (
            alpha_dimer * (1.0 + self.J * beta_qd) / denominator
        )
        mu_qd_over_e = beta_qd * (1.0 + self.J * alpha_dimer) / denominator
        return (
            (mu_dimer_over_e + mu_qd_over_e) / self.params.eps_m,
            alpha_dimer / self.params.eps_m,
            beta_qd / self.params.eps_m,
        )

    def initial_state(self) -> np.ndarray:
        state = np.zeros(2 * self.n_modes + 3, dtype=float)
        state[2 * self.n_modes] = -1.0
        return state

    def rhs(self, t_au: float, state: np.ndarray, pulse: GaussianPulse) -> np.ndarray:
        p = self.params
        q = state[: 2 * self.n_modes : 2]
        velocity = state[1 : 2 * self.n_modes : 2]
        W, Q, P = state[2 * self.n_modes : 2 * self.n_modes + 3]
        incident = float(pulse.field(t_au))
        local_field = p.qd_local_field_factor
        mu_qd = local_field * p.d_au * P
        drive = (
            incident
            + self.J * mu_qd
            + self.K * self.C * float(np.sum(q))
        ) / self._symmetric_instantaneous_denominator
        mu_each = self.C * (self.fit.alpha_inf * drive + float(np.sum(q)))
        qd_field = local_field * (incident + 2.0 * self.J * mu_each)
        rabi = 2.0 * p.d_au * qd_field

        derivative = np.zeros_like(state)
        for index, (coordinate, speed, strength, omega, gamma) in enumerate(
            zip(
                q,
                velocity,
                self.fit.strengths_au2,
                self.fit.omega_modes_au,
                self.fit.gamma_modes_au,
            )
        ):
            derivative[2 * index] = speed
            derivative[2 * index + 1] = (
                strength * drive - gamma * speed - omega**2 * coordinate
            )
        derivative[2 * self.n_modes] = rabi * Q - p.gamma_au * (W + 1.0)
        derivative[2 * self.n_modes + 1] = (
            -p.omega0_au * P - rabi * W - p.Gamma_au * Q
        )
        derivative[2 * self.n_modes + 2] = p.omega0_au * Q - p.Gamma_au * P
        return derivative

    def reconstruct(
        self,
        t_au: np.ndarray,
        state: np.ndarray,
        pulse: GaussianPulse,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        p = self.params
        q = state[: 2 * self.n_modes : 2]
        P = state[2 * self.n_modes + 2]
        incident = pulse.field(t_au)
        mu_qd = p.qd_local_field_factor * p.d_au * P
        drive = (
            incident + self.J * mu_qd + self.K * self.C * np.sum(q, axis=0)
        ) / self._symmetric_instantaneous_denominator
        mu_each = self.C * (self.fit.alpha_inf * drive + np.sum(q, axis=0))
        total = 2.0 * mu_each + mu_qd
        return incident, mu_each, mu_qd, total

    def _numerical_jacobian(self) -> np.ndarray:
        ground = self.initial_state()
        zero_pulse = GaussianPulse(
            E0_au=1e-30,
            omegaL_au=self.params.omega0_au,
            tau_au=float(fs_to_au(20.0)),
            tau_kind="fwhm_intensity",
        )
        size = ground.size
        jacobian = np.empty((size, size), dtype=float)
        for column in range(size):
            step = 1e-7 * max(1.0, abs(float(ground[column])))
            plus = ground.copy()
            minus = ground.copy()
            plus[column] += step
            minus[column] -= step
            jacobian[:, column] = (
                self.rhs(0.0, plus, zero_pulse)
                - self.rhs(0.0, minus, zero_pulse)
            ) / (2.0 * step)
        return jacobian

    def _antisymmetric_jacobian(self) -> np.ndarray:
        size = 2 * self.n_modes
        jacobian = np.zeros((size, size), dtype=float)
        drive_coeff = -self.K * self.C / self._antisymmetric_instantaneous_denominator
        for index, (strength, omega, gamma) in enumerate(
            zip(
                self.fit.strengths_au2,
                self.fit.omega_modes_au,
                self.fit.gamma_modes_au,
            )
        ):
            q_index = 2 * index
            v_index = q_index + 1
            jacobian[q_index, v_index] = 1.0
            jacobian[v_index, v_index] = -gamma
            jacobian[v_index, q_index] = -omega**2
            jacobian[v_index, 0 : 2 * self.n_modes : 2] += (
                strength * drive_coeff
            )
        return jacobian

    def _stability_audit(self) -> StabilityAudit:
        symmetric_poles = np.linalg.eigvals(self._numerical_jacobian())
        antisymmetric_poles = np.linalg.eigvals(self._antisymmetric_jacobian())
        scale = max(
            self.params.omega0_au,
            float(np.max(self.fit.omega_modes_au)),
            1e-15,
        )
        tolerance = 1e-10 * scale
        symmetric_poles = np.asarray(symmetric_poles, dtype=complex)
        antisymmetric_poles = np.asarray(antisymmetric_poles, dtype=complex)
        symmetric_poles.setflags(write=False)
        antisymmetric_poles.setflags(write=False)
        return StabilityAudit(
            symmetric_poles_au=symmetric_poles,
            antisymmetric_poles_au=antisymmetric_poles,
            symmetric_stable=bool(np.max(symmetric_poles.real) <= tolerance),
            antisymmetric_stable=bool(
                np.max(antisymmetric_poles.real) <= tolerance
            ),
            tolerance_au=float(tolerance),
        )

    def coherent_decay_rate_au(self) -> float:
        jacobian = self._numerical_jacobian()
        W_index = 2 * self.n_modes
        coherent = np.delete(np.delete(jacobian, W_index, axis=0), W_index, axis=1)
        symmetric_rate = -float(np.max(np.linalg.eigvals(coherent).real))
        antisymmetric_rate = -float(
            np.max(self.stability.antisymmetric_poles_au.real)
        )
        rate = min(symmetric_rate, antisymmetric_rate)
        if not np.isfinite(rate) or rate <= 0.0:
            raise RuntimeError("No decaying coherent dimer branch was found.")
        return float(rate)


def build_native_dimer_model(
    profile: Shah2013Profile,
    *,
    decay_profile: DecayProfile = "purcell_cp",
    refit: bool = False,
    verbose: bool = False,
) -> SymmetricDimerQDPlasmonModel:
    params = build_shah_params(profile, decay_profile)
    if refit:
        native_single = HybridQDPlasmonModel(
            params,
            orientation="long",
            n_modes=10,
            fit_window_eV=(0.8, 3.0),
            max_fit_pointwise_relative_error=0.051,
            verbose=verbose,
        )
        fit = native_single.fit
        provenance = "refitted by HybridQDPlasmonModel"
    else:
        fit = _cached_shah_fit(params)
        provenance = "cached output of HybridQDPlasmonModel N=10 fit"
    return SymmetricDimerQDPlasmonModel(
        params,
        fit,
        mnp_center_distance_nm=profile.mnp_center_distance_nm,
        fit_provenance=provenance,
    )


def peak_field_from_intensity_au(
    intensity_w_cm2: float,
    eps_m: float,
) -> float:
    if not np.isfinite(intensity_w_cm2) or intensity_w_cm2 <= 0.0:
        raise ValueError("Intensity must be finite and positive.")
    field_si = np.sqrt(
        2.0 * intensity_w_cm2 * 1e4
        / (np.sqrt(eps_m) * epsilon_0 * C_SI)
    )
    return float(field_si_to_au(field_si))


def pulse_from_fluence(
    profile: Shah2013Profile,
    fluence_j_cm2: float,
) -> GaussianPulse:
    if not np.isfinite(fluence_j_cm2) or fluence_j_cm2 <= 0.0:
        raise ValueError("Fluence must be finite and positive.")
    tau_au = float(fs_to_au(profile.pulse_fwhm_intensity_fs))
    sigma_au = tau_au / (2.0 * np.sqrt(np.log(2.0)))
    sigma_s = sigma_au * AU_TIME_S
    omega_au = float(eV_to_au(profile.transition_energy_ev))
    overlap = np.exp(-(omega_au * sigma_au) ** 2)
    fluence_j_m2 = fluence_j_cm2 * 1e4
    denominator = (
        np.sqrt(profile.eps_environment)
        * epsilon_0
        * C_SI
        * 0.5
        * np.sqrt(np.pi)
        * sigma_s
        * (1.0 + overlap)
    )
    field_si = np.sqrt(fluence_j_m2 / denominator)
    pulse = GaussianPulse(
        E0_au=float(field_si_to_au(field_si)),
        omegaL_au=omega_au,
        tau_au=tau_au,
        tau_kind="fwhm_intensity",
    )
    reconstructed = pulse.fluence_j_cm2(eps_m=profile.eps_environment)
    if not np.isclose(reconstructed, fluence_j_cm2, rtol=2e-13, atol=0.0):
        raise RuntimeError("Internal pulse-fluence normalization mismatch.")
    return pulse


def _harmonic_state_for_inversion(
    model: SymmetricDimerQDPlasmonModel,
    *,
    energy_ev: float,
    field_amplitude_au: float,
    inversion: float,
    response: MNPResponse,
    alpha_dimer_au: complex | None = None,
    bloch_factor_au: complex | None = None,
) -> tuple[float, complex, complex, complex, complex, complex]:
    p = model.params
    omega = float(eV_to_au(energy_ev))
    alpha_dimer = (
        complex(model.alpha_bare_dimer_au(energy_ev, response=response))
        if alpha_dimer_au is None
        else complex(alpha_dimer_au)
    )
    bloch_factor = (
        p.omega0_au
        / (p.omega0_au**2 + (p.Gamma_au - 1j * omega) ** 2)
        if bloch_factor_au is None
        else complex(bloch_factor_au)
    )
    local = p.qd_local_field_factor
    denominator = (
        1.0
        + 2.0
        * p.d_au**2
        * local**2
        * inversion
        * bloch_factor
        * model.J**2
        * alpha_dimer
    )
    P_amplitude = (
        -2.0
        * p.d_au
        * local
        * inversion
        * bloch_factor
        * (1.0 + model.J * alpha_dimer)
        * field_amplitude_au
        / denominator
    )
    mu_qd = local * p.d_au * P_amplitude
    mu_dimer = alpha_dimer * (field_amplitude_au + model.J * mu_qd)
    local_field = local * (field_amplitude_au + model.J * mu_dimer)
    rabi_amplitude = 2.0 * p.d_au * local_field
    Q_amplitude = (p.Gamma_au - 1j * omega) * P_amplitude / p.omega0_au
    population_residual = (
        0.5 * np.real(rabi_amplitude * np.conj(Q_amplitude))
        - p.gamma_au * (inversion + 1.0)
    )
    total_dipole = mu_dimer + mu_qd
    return (
        float(population_residual),
        P_amplitude,
        Q_amplitude,
        mu_qd,
        0.5 * mu_dimer,
        total_dipole,
    )


def solve_cw_harmonic_state(
    model: SymmetricDimerQDPlasmonModel,
    *,
    energy_ev: float,
    intensity_w_cm2: float,
    response: MNPResponse = "modal",
    preferred_inversion: float | None = None,
) -> HarmonicState:
    field_amplitude = peak_field_from_intensity_au(
        intensity_w_cm2,
        model.params.eps_m,
    )
    p = model.params
    omega = float(eV_to_au(energy_ev))
    alpha_dimer = complex(model.alpha_bare_dimer_au(energy_ev, response=response))
    bloch_factor = p.omega0_au / (
        p.omega0_au**2 + (p.Gamma_au - 1j * omega) ** 2
    )

    def residual(inversion: float) -> float:
        return _harmonic_state_for_inversion(
            model,
            energy_ev=energy_ev,
            field_amplitude_au=field_amplitude,
            inversion=inversion,
            response=response,
            alpha_dimer_au=alpha_dimer,
            bloch_factor_au=bloch_factor,
        )[0]

    inversion_grid = np.linspace(-1.0, 0.0, 401)
    local = p.qd_local_field_factor
    denominator = (
        1.0
        + 2.0
        * p.d_au**2
        * local**2
        * inversion_grid
        * bloch_factor
        * model.J**2
        * alpha_dimer
    )
    P_grid = (
        -2.0
        * p.d_au
        * local
        * inversion_grid
        * bloch_factor
        * (1.0 + model.J * alpha_dimer)
        * field_amplitude
        / denominator
    )
    mu_qd_grid = local * p.d_au * P_grid
    mu_dimer_grid = alpha_dimer * (field_amplitude + model.J * mu_qd_grid)
    local_field_grid = local * (field_amplitude + model.J * mu_dimer_grid)
    rabi_grid = 2.0 * p.d_au * local_field_grid
    Q_grid = (p.Gamma_au - 1j * omega) * P_grid / p.omega0_au
    residuals = (
        0.5 * np.real(rabi_grid * np.conj(Q_grid))
        - p.gamma_au * (inversion_grid + 1.0)
    )
    roots: list[float] = []
    for left, right, f_left, f_right in zip(
        inversion_grid[:-1],
        inversion_grid[1:],
        residuals[:-1],
        residuals[1:],
    ):
        if f_left == 0.0:
            roots.append(float(left))
        if f_left * f_right < 0.0:
            roots.append(float(brentq(residual, left, right, xtol=1e-13)))
    if residuals[-1] == 0.0:
        roots.append(0.0)
    roots = sorted(set(round(value, 13) for value in roots))
    if not roots:
        raise RuntimeError("No physical CW inversion root in [-1, 0].")
    target = -1.0 if preferred_inversion is None else preferred_inversion
    inversion = min(roots, key=lambda value: abs(value - target))
    _, P, Q, mu_qd, mu_each, total = _harmonic_state_for_inversion(
        model,
        energy_ev=energy_ev,
        field_amplitude_au=field_amplitude,
        inversion=inversion,
        response=response,
        alpha_dimer_au=alpha_dimer,
        bloch_factor_au=bloch_factor,
    )
    effective_alpha = total / (model.params.eps_m * field_amplitude)
    work_loss = float(
        quasistatic_work_loss_cross_section_cm2(
            np.asarray([effective_alpha]),
            np.asarray([eV_to_au(energy_ev)]),
            model.params.eps_m,
        )[0]
    )
    # The RWA density matrix retains the co-rotating optical coherence only.
    # With the present Bloch convention Q=-i*P on the positive-frequency
    # branch, so (P+iQ)/2 is its physical transverse Bloch amplitude.
    transverse = 0.5 * (P + 1j * Q)
    max_radius = float(np.sqrt(inversion**2 + np.abs(transverse) ** 2))
    if max_radius > 1.0 + 5e-5:
        raise RuntimeError(
            "The RWA steady state left the Bloch ball: "
            f"radius={max_radius:.9g}."
        )
    return HarmonicState(
        energy_ev=float(energy_ev),
        intensity_w_cm2=float(intensity_w_cm2),
        inversion=float(inversion),
        excited_population=float(0.5 * (inversion + 1.0)),
        qd_bloch_p_amplitude=P,
        qd_bloch_q_amplitude=Q,
        qd_dipole_au=mu_qd,
        each_mnp_dipole_au=mu_each,
        total_dipole_au=total,
        effective_alpha_au=effective_alpha,
        paper_work_loss_cm2=work_loss,
        root_count=len(roots),
        max_periodic_bloch_radius=max_radius,
    )


def scan_cw_spectrum(
    model: SymmetricDimerQDPlasmonModel,
    energies_ev: np.ndarray,
    intensity_w_cm2: float,
    *,
    response: MNPResponse = "modal",
) -> list[HarmonicState]:
    states: list[HarmonicState] = []
    previous = None
    for energy in np.asarray(energies_ev, dtype=float):
        state = solve_cw_harmonic_state(
            model,
            energy_ev=float(energy),
            intensity_w_cm2=intensity_w_cm2,
            response=response,
            preferred_inversion=previous,
        )
        states.append(state)
        previous = state.inversion
    return states


def _tail_ratio(total_dipole: np.ndarray) -> float:
    count = max(8, total_dipole.size // 100)
    scale = max(float(np.max(np.abs(total_dipole))), np.finfo(float).tiny)
    return float(np.max(np.abs(total_dipole[-count:])) / scale)


def solve_pulse_trace(
    model: SymmetricDimerQDPlasmonModel,
    profile: Shah2013Profile,
    fluence_j_cm2: float,
    *,
    rtol: float = 2e-8,
    atol: float = 2e-10,
    samples_per_fastest_cycle: int = 24,
    tail_decay_times: float = 8.0,
) -> PulseTrace:
    pulse = pulse_from_fluence(profile, fluence_j_cm2)
    spectral_fraction = pulse.positive_frequency_spectral_fraction(
        model.fit_window_ev
    )
    if spectral_fraction < 0.999:
        raise ValueError(
            "The 20 fs pulse is not covered by the modal fit window: "
            f"fraction={spectral_fraction:.9g}."
        )
    fastest = max(
        pulse.omegaL_au,
        model.params.omega0_au,
        float(np.max(model.fit.omega_modes_au)),
        float(np.max(np.abs(model.stability.symmetric_poles_au))),
        float(np.max(np.abs(model.stability.antisymmetric_poles_au))),
    )
    max_step = float(2.0 * np.pi / (samples_per_fastest_cycle * fastest))
    t_start = float(-8.0 * pulse.sigma_t_au)
    coherent_rate = model.coherent_decay_rate_au()
    t_end = float(
        max(8.0 * pulse.sigma_t_au, tail_decay_times / coherent_rate)
    )
    solution = solve_ivp(
        lambda t, y: model.rhs(t, y, pulse),
        (t_start, t_end),
        model.initial_state(),
        method="DOP853",
        rtol=rtol,
        atol=atol,
        max_step=max_step,
        dense_output=False,
    )
    if not solution.success:
        raise RuntimeError(solution.message)
    field, mu_each, mu_qd, total = model.reconstruct(
        solution.t,
        solution.y,
        pulse,
    )
    W, Q, P = solution.y[2 * model.n_modes : 2 * model.n_modes + 3]
    radius = np.sqrt(W**2 + Q**2 + P**2)
    max_radius = float(np.max(radius))
    min_eigenvalue = float(np.min(0.5 * (1.0 - radius)))
    if min_eigenvalue < -1e-6:
        raise RuntimeError(
            "Pulse trajectory violates density-matrix positivity: "
            f"min eigenvalue={min_eigenvalue:.9g}."
        )
    tail = _tail_ratio(total)
    if tail > 5e-4:
        raise RuntimeError(
            "Post-pulse coherent tail is not converged: "
            f"tail ratio={tail:.6g}."
        )
    return PulseTrace(
        fluence_j_cm2=float(fluence_j_cm2),
        t_au=np.asarray(solution.t),
        y=np.asarray(solution.y),
        field_au=np.asarray(field),
        each_mnp_dipole_au=np.asarray(mu_each),
        qd_dipole_au=np.asarray(mu_qd),
        total_dipole_au=np.asarray(total),
        max_bloch_radius=max_radius,
        min_density_eigenvalue=min_eigenvalue,
        tail_ratio=tail,
        solver_nfev=int(solution.nfev),
        max_step_au=max_step,
    )


def pulse_spectral_alpha_au(
    trace: PulseTrace,
    profile: Shah2013Profile,
    energies_ev: np.ndarray,
) -> np.ndarray:
    energies = np.asarray(energies_ev, dtype=float)
    omega = np.asarray(eV_to_au(energies), dtype=float)
    numerator = np.empty(energies.shape, dtype=complex)
    denominator = np.empty(energies.shape, dtype=complex)
    for start in range(0, energies.size, 32):
        stop = min(start + 32, energies.size)
        # The native harmonic response uses exp(-i*omega*t), so recovering its
        # positive-frequency amplitude from a real trace requires exp(+i*omega*t).
        # This is also the sign for which a passive alpha has Im(alpha)>=0.
        phase = np.exp(1j * omega[start:stop, None] * trace.t_au[None, :])
        numerator[start:stop] = np.trapezoid(
            phase * trace.total_dipole_au[None, :],
            trace.t_au,
            axis=1,
        )
        denominator[start:stop] = np.trapezoid(
            phase * trace.field_au[None, :],
            trace.t_au,
            axis=1,
        )
    denominator_scale = max(float(np.max(np.abs(denominator))), np.finfo(float).tiny)
    reliable = np.abs(denominator) >= 1e-8 * denominator_scale
    result = np.full(energies.shape, np.nan + 1j * np.nan, dtype=complex)
    result[reliable] = numerator[reliable] / (
        profile.eps_environment * denominator[reliable]
    )
    return result


def _unpack_envelope_state(
    state: np.ndarray,
    n_modes: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    modal = state[: 2 * n_modes : 2] + 1j * state[1 : 2 * n_modes : 2]
    offset = 2 * n_modes
    # Strict optical RWA: keep only R=(P+iQ)/2.  On this co-rotating branch
    # P=R and Q=-iR; the discarded orthogonal combination oscillates near
    # 2*omega_L in the rotating frame.
    P = state[offset] + 1j * state[offset + 1]
    Q = -1j * P
    W = state[offset + 2]
    return modal, P, Q, W


def _pack_complex_derivative(
    modal: np.ndarray,
    coherence: complex,
    W: float,
) -> np.ndarray:
    derivative = np.empty(2 * modal.size + 3, dtype=float)
    derivative[: 2 * modal.size : 2] = modal.real
    derivative[1 : 2 * modal.size : 2] = modal.imag
    offset = 2 * modal.size
    derivative[offset : offset + 3] = [
        coherence.real,
        coherence.imag,
        W,
    ]
    return derivative


def _rwa_periodic_bloch_radius(
    inversion: np.ndarray,
    P: np.ndarray,
    Q: np.ndarray,
) -> np.ndarray:
    """Bloch radius of the retained co-rotating optical coherence.

    For a positive-frequency Bloch solution the harmonic amplitudes obey
    Q=-i*P.  The physical transverse amplitude is therefore
    (P+i*Q)/2.  The orthogonal combination is the counter-rotating component
    discarded by RWA and must not be counted as a second coherence.
    """

    transverse = 0.5 * (P + 1j * Q)
    return np.sqrt(np.maximum(0.0, inversion**2 + np.abs(transverse) ** 2))


def solve_pulse_envelope_trace(
    model: SymmetricDimerQDPlasmonModel,
    profile: Shah2013Profile,
    fluence_j_cm2: float,
    *,
    rtol: float = 2e-8,
    atol: float = 2e-10,
    tail_decay_times: float = 8.0,
) -> PulseEnvelopeTrace:
    """Integrate the native modal/Bloch equations in a rotating frame.

    The second-order modal equations are reduced to their positive-frequency
    slowly varying amplitudes.  At steady state this realization gives exactly
    the same Lorentz denominator at the carrier.  Across the 20-fs bandwidth it
    is the usual first-order RWA used and explicitly checked by Shah et al.
    """

    pulse = pulse_from_fluence(profile, fluence_j_cm2)
    spectral_fraction = pulse.positive_frequency_spectral_fraction(
        model.fit_window_ev
    )
    if spectral_fraction < 0.999:
        raise ValueError(
            "The 20 fs pulse is not covered by the modal fit window: "
            f"fraction={spectral_fraction:.9g}."
        )
    omega_l = pulse.omegaL_au
    sigma = pulse.sigma_t_au
    p = model.params

    initial = np.zeros(2 * model.n_modes + 3, dtype=float)
    initial[-1] = -1.0

    def rhs(t_au: float, state: np.ndarray) -> np.ndarray:
        modal, P, Q, W = _unpack_envelope_state(state, model.n_modes)
        field_envelope = pulse.E0_au * np.exp(-0.5 * (t_au / sigma) ** 2)
        mu_qd = p.qd_local_field_factor * p.d_au * P
        drive = (
            field_envelope
            + model.J * mu_qd
            + model.K * model.C * np.sum(modal)
        ) / model._symmetric_instantaneous_denominator
        mu_each = model.C * (model.fit.alpha_inf * drive + np.sum(modal))
        qd_field = p.qd_local_field_factor * (
            field_envelope + 2.0 * model.J * mu_each
        )
        rabi = 2.0 * p.d_au * qd_field
        modal_denominator = (
            model.fit.omega_modes_au**2
            - omega_l**2
            - 1j * model.fit.gamma_modes_au * omega_l
        )
        modal_derivative = (
            model.fit.strengths_au2 * drive - modal_denominator * modal
        ) / (model.fit.gamma_modes_au - 2j * omega_l)
        coherence_derivative = (
            (1j * (omega_l - p.omega0_au) - p.Gamma_au) * P
            - 0.5j * rabi * W
        )
        W_derivative = (
            0.5 * np.real(rabi * np.conj(Q)) - p.gamma_au * (W + 1.0)
        )
        return _pack_complex_derivative(
            modal_derivative,
            coherence_derivative,
            float(W_derivative),
        )

    t_start = float(-8.0 * sigma)
    t_end = float(max(8.0 * sigma, tail_decay_times / model.coherent_decay_rate_au()))
    solution = solve_ivp(
        rhs,
        (t_start, t_end),
        initial,
        method="Radau",
        rtol=rtol,
        atol=atol,
        dense_output=False,
    )
    if not solution.success:
        raise RuntimeError(solution.message)
    modal, P, Q, W = _unpack_envelope_state(solution.y, model.n_modes)
    field_envelope = pulse.E0_au * np.exp(-0.5 * (solution.t / sigma) ** 2)
    mu_qd = p.qd_local_field_factor * p.d_au * P
    drive = (
        field_envelope
        + model.J * mu_qd
        + model.K * model.C * np.sum(modal, axis=0)
    ) / model._symmetric_instantaneous_denominator
    mu_each = model.C * (model.fit.alpha_inf * drive + np.sum(modal, axis=0))
    total = 2.0 * mu_each + mu_qd
    radius = _rwa_periodic_bloch_radius(W, P, Q)
    max_radius = float(np.max(radius))
    min_eigenvalue = float(np.min(0.5 * (1.0 - radius)))
    if min_eigenvalue < -1e-6:
        raise RuntimeError(
            "RWA pulse trajectory violates density-matrix positivity: "
            f"min eigenvalue={min_eigenvalue:.9g}."
        )
    tail = _tail_ratio(total)
    if tail > 5e-4:
        raise RuntimeError(
            "RWA post-pulse coherent tail is not converged: "
            f"tail ratio={tail:.6g}."
        )
    return PulseEnvelopeTrace(
        fluence_j_cm2=float(fluence_j_cm2),
        carrier_omega_au=float(omega_l),
        t_au=np.asarray(solution.t),
        state=np.asarray(solution.y),
        field_envelope_au=np.asarray(field_envelope, dtype=complex),
        each_mnp_envelope_au=np.asarray(mu_each, dtype=complex),
        qd_envelope_au=np.asarray(mu_qd, dtype=complex),
        total_envelope_au=np.asarray(total, dtype=complex),
        inversion=np.asarray(W, dtype=float),
        max_bloch_radius=max_radius,
        min_density_eigenvalue=min_eigenvalue,
        tail_ratio=tail,
        solver_nfev=int(solution.nfev),
    )


def pulse_envelope_spectral_alpha_au(
    trace: PulseEnvelopeTrace,
    profile: Shah2013Profile,
    energies_ev: np.ndarray,
) -> np.ndarray:
    energies = np.asarray(energies_ev, dtype=float)
    detuning = np.asarray(eV_to_au(energies), dtype=float) - trace.carrier_omega_au
    numerator = np.empty(energies.shape, dtype=complex)
    denominator = np.empty(energies.shape, dtype=complex)
    for start in range(0, energies.size, 32):
        stop = min(start + 32, energies.size)
        phase = np.exp(1j * detuning[start:stop, None] * trace.t_au[None, :])
        numerator[start:stop] = np.trapezoid(
            phase * trace.total_envelope_au[None, :],
            trace.t_au,
            axis=1,
        )
        denominator[start:stop] = np.trapezoid(
            phase * trace.field_envelope_au[None, :],
            trace.t_au,
            axis=1,
        )
    scale = max(float(np.max(np.abs(denominator))), np.finfo(float).tiny)
    reliable = np.abs(denominator) >= 1e-8 * scale
    alpha = np.full(energies.shape, np.nan + 1j * np.nan, dtype=complex)
    alpha[reliable] = numerator[reliable] / (
        profile.eps_environment * denominator[reliable]
    )
    return alpha


def pulse_envelope_work_loss_spectrum_cm2(
    trace: PulseEnvelopeTrace,
    profile: Shah2013Profile,
    energies_ev: np.ndarray,
) -> np.ndarray:
    alpha = pulse_envelope_spectral_alpha_au(trace, profile, energies_ev)
    return np.asarray(
        quasistatic_work_loss_cross_section_cm2(
            alpha,
            np.asarray(eV_to_au(energies_ev), dtype=float),
            profile.eps_environment,
        ),
        dtype=float,
    )


def pulse_work_loss_spectrum_cm2(
    trace: PulseTrace,
    profile: Shah2013Profile,
    energies_ev: np.ndarray,
) -> np.ndarray:
    alpha = pulse_spectral_alpha_au(trace, profile, energies_ev)
    values = quasistatic_work_loss_cross_section_cm2(
        alpha,
        np.asarray(eV_to_au(energies_ev), dtype=float),
        profile.eps_environment,
    )
    return np.asarray(values, dtype=float)


def _write_csv(path: Path, rows: Iterable[dict]) -> None:
    rows = list(rows)
    if not rows:
        raise ValueError(f"Cannot write empty CSV: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def _article_pdf_hash(path: Path) -> str | None:
    if not path.exists():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _nearest_local_extremum_index(
    energies_ev: np.ndarray,
    values: np.ndarray,
    *,
    center_ev: float,
    kind: Literal["minimum", "maximum"],
    half_window_ev: float = 0.03,
) -> int | None:
    """Locate a genuine local Fano extremum near the QD transition.

    A global minimum over the full plotting window is usually just the low-
    energy edge of the broad plasmon band and must not be labelled as the
    narrow Fano minimum.
    """

    energies = np.asarray(energies_ev, dtype=float)
    observable = np.asarray(values, dtype=float)
    sign = -1.0 if kind == "minimum" else 1.0
    candidates, _ = find_peaks(sign * observable)
    candidates = candidates[
        np.abs(energies[candidates] - center_ev) <= half_window_ev
    ]
    if candidates.size == 0:
        return None
    return int(
        candidates[
            np.argmin(np.abs(energies[candidates] - center_ev))
        ]
    )


def _plot_figure1(
    energies: np.ndarray,
    coupled: np.ndarray,
    bare: np.ndarray,
    path: Path,
) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    ax.plot(energies, coupled / 1e-11, label="native Au--QD--Au")
    ax.plot(energies, bare / 1e-11, "--", label="native bare Au dimer")
    ax.axvline(2.042, color="0.5", lw=1, ls=":")
    ax.set(
        xlabel="Photon energy (eV)",
        ylabel=r"$k\,\mathrm{Im}\alpha/\epsilon_0$ ($10^{-11}$ cm$^2$)",
    )
    ax.grid(alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _plot_figure2(
    energies: np.ndarray,
    cw_spectra: dict[float, list[HarmonicState]],
    intensity_rows: list[dict],
    path: Path,
) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12.4, 4.8))
    for offset, (intensity, states) in enumerate(sorted(cw_spectra.items())):
        values = np.asarray([state.paper_work_loss_cm2 for state in states])
        axes[0].plot(
            energies,
            values / 1e-11 + 2.0 * offset,
            label=f"{intensity / 1e3:g} kW/cm²",
        )
    axes[0].set(
        xlabel="Photon energy (eV)",
        ylabel=(
            r"offset $k\,\mathrm{Im}\alpha/\epsilon_0$ "
            r"($10^{-11}$ cm$^2$)"
        ),
    )
    axes[0].legend()
    axes[0].grid(alpha=0.25)
    axes[1].semilogx(
        [row["intensity_w_cm2"] for row in intensity_rows],
        [row["paper_work_loss_cm2"] / 1e-11 for row in intensity_rows],
    )
    axes[1].set(
        xlabel="Intensity (W/cm²)",
        ylabel=(
            r"resonant $k\,\mathrm{Im}\alpha/\epsilon_0$ "
            r"($10^{-11}$ cm$^2$)"
        ),
    )
    axes[1].grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _plot_figure3(
    energies: np.ndarray,
    highlighted_spectra: dict[float, np.ndarray],
    fluence_rows: list[dict],
    path: Path,
) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(16.5, 4.8))
    for offset, (fluence, values) in enumerate(sorted(highlighted_spectra.items())):
        axes[0].plot(
            energies,
            values / 1e-11 + 2.0 * offset,
            label=f"{fluence * 1e9:g} nJ/cm²",
        )
    axes[0].set(
        xlabel="Photon energy (eV)",
        ylabel=(
            r"offset pulse $k\,\mathrm{Im}\alpha/\epsilon_0$ "
            r"($10^{-11}$ cm$^2$)"
        ),
    )
    axes[0].legend(fontsize=8)
    axes[0].grid(alpha=0.25)
    fluence = np.asarray([row["fluence_j_cm2"] for row in fluence_rows])
    cross_section = np.asarray(
        [row["resonant_paper_work_loss_cm2"] for row in fluence_rows]
    )
    pulse_area = np.asarray([row["operational_pulse_area"] for row in fluence_rows])
    axes[1].semilogx(fluence, cross_section / 1e-11)
    axes[1].set(
        xlabel="Fluence (J/cm²)",
        ylabel=(
            r"resonant $k\,\mathrm{Im}\alpha/\epsilon_0$ "
            r"($10^{-11}$ cm$^2$)"
        ),
    )
    axes[1].grid(alpha=0.25)
    axes[2].plot(pulse_area / np.pi, cross_section / 1e-11)
    axes[2].set(
        xlabel=r"Operational pulse area / $\pi$",
        ylabel=(
            r"resonant $k\,\mathrm{Im}\alpha/\epsilon_0$ "
            r"($10^{-11}$ cm$^2$)"
        ),
    )
    axes[2].grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _plot_figure4(
    traces: dict[float, PulseEnvelopeTrace],
    path: Path,
) -> None:
    fluences = sorted(traces)
    fig, axes = plt.subplots(3, len(fluences), figsize=(12.2, 10.0), sharex=True)
    if len(fluences) == 1:
        axes = np.asarray(axes)[:, None]
    for column, fluence in enumerate(fluences):
        trace = traces[fluence]
        time_fs = np.asarray(au_to_fs(trace.t_au), dtype=float)
        mask = (time_fs >= -50.0) & (time_fs <= 150.0)
        uniform_time = np.linspace(-50.0, 150.0, 5001)
        carrier_phase = np.exp(
            -1j
            * trace.carrier_omega_au
            * np.asarray(fs_to_au(uniform_time), dtype=float)
        )

        def interpolate_complex(values: np.ndarray) -> np.ndarray:
            return np.interp(uniform_time, time_fs[mask], values[mask].real) + 1j * np.interp(
                uniform_time,
                time_fs[mask],
                values[mask].imag,
            )

        field_envelope = interpolate_complex(trace.field_envelope_au)
        qd_envelope = interpolate_complex(trace.qd_envelope_au)
        mnp_envelope = 2.0 * interpolate_complex(trace.each_mnp_envelope_au)
        field = np.real(field_envelope * carrier_phase)
        qd = np.real(qd_envelope * carrier_phase)
        mnp = np.real(mnp_envelope * carrier_phase)
        W = np.interp(uniform_time, time_fs[mask], trace.inversion[mask])
        population = 0.5 * (W + 1.0)
        field_si = np.asarray(field_au_to_si(field)) / 1e6
        qd_debye = qd * AU_DIPOLE_C_M / DEBYE_C_M
        mnp_kdebye = mnp * AU_DIPOLE_C_M / DEBYE_C_M / 1e3

        def visible_phase_lag(response: np.ndarray) -> np.ndarray:
            """Return a carrier-referenced phase only while it is observable."""

            amplitude = np.abs(response)
            cutoff = 0.02 * float(np.max(amplitude))
            lag = np.mod(
                np.angle(field_envelope) - np.angle(response),
                2.0 * np.pi,
            )
            return np.where(amplitude >= cutoff, lag, np.nan)

        axes[0, column].plot(uniform_time, field_si, color="0.25", lw=0.7)
        population_axis = axes[0, column].twinx()
        population_axis.plot(uniform_time, population, color="tab:red")
        population_axis.set_ylabel("QD population", color="tab:red")
        axes[0, column].set_ylabel("Field (MV/m)")
        axes[0, column].set_title(f"{fluence * 1e9:g} nJ/cm²")
        axes[1, column].plot(uniform_time, qd_debye, color="0.25", lw=0.7)
        qd_phase_axis = axes[1, column].twinx()
        qd_phase_axis.plot(
            uniform_time,
            visible_phase_lag(qd_envelope),
            color="tab:red",
        )
        qd_phase_axis.set_ylim(0.0, 2.0 * np.pi)
        qd_phase_axis.set_ylabel("QD phase lag", color="tab:red")
        axes[1, column].set_ylabel("QD dipole (D)")
        axes[2, column].plot(uniform_time, mnp_kdebye, color="0.25", lw=0.7)
        mnp_phase_axis = axes[2, column].twinx()
        mnp_phase_axis.plot(
            uniform_time,
            visible_phase_lag(mnp_envelope),
            color="tab:red",
        )
        mnp_phase_axis.set_ylim(0.0, 2.0 * np.pi)
        mnp_phase_axis.set_ylabel("dimer phase lag", color="tab:red")
        axes[2, column].set_ylabel("Dimer dipole (10³ D)")
        axes[2, column].set_xlabel("Time from pulse center (fs)")
        for row in range(3):
            axes[row, column].grid(alpha=0.2)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def run_comparison(
    *,
    profile: Shah2013Profile,
    output_dir: Path,
    article_pdf: Path,
    decay_profile: DecayProfile,
    response: MNPResponse,
    refit: bool,
    energy_points: int,
    intensity_points: int,
    fluence_points: int,
    verbose: bool,
) -> dict:
    if energy_points < 101 or intensity_points < 9 or fluence_points < 9:
        raise ValueError("Comparison grids are too small for the requested figures.")
    energies = np.linspace(1.94, 2.14, energy_points)
    energy_step_mev = float((energies[1] - energies[0]) * 1000.0)
    _, gamma2_mev = profile.rates_mev(decay_profile)
    if energy_step_mev > gamma2_mev / 4.0:
        raise ValueError(
            "The Shah energy grid does not resolve Gamma2/4: "
            f"step={energy_step_mev:.6g} meV, Gamma2/4={gamma2_mev / 4:.6g} meV."
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    model = build_native_dimer_model(
        profile,
        decay_profile=decay_profile,
        refit=refit,
        verbose=verbose,
    )

    coupled_alpha, bare_alpha, _ = model.linear_coupled_alpha_au(
        energies,
        response=response,
    )
    omega = np.asarray(eV_to_au(energies), dtype=float)
    linear_work = quasistatic_work_loss_cross_section_cm2(
        coupled_alpha,
        omega,
        profile.eps_environment,
    )
    bare_work = quasistatic_work_loss_cross_section_cm2(
        bare_alpha,
        omega,
        profile.eps_environment,
    )
    _write_csv(
        output_dir / "figure1_linear_spectrum.csv",
        [
            {
                "energy_ev": float(energy),
                "native_coupled_work_loss_cm2": float(coupled),
                "native_bare_dimer_work_loss_cm2": float(bare),
                "response": response,
            }
            for energy, coupled, bare in zip(energies, linear_work, bare_work)
        ],
    )
    _plot_figure1(energies, linear_work, bare_work, output_dir / "figure1_native_dimer.png")

    cw_spectra = {
        intensity: scan_cw_spectrum(
            model,
            energies,
            intensity,
            response=response,
        )
        for intensity in profile.cw_intensities_w_cm2
    }
    cw_rows = []
    for intensity, states in cw_spectra.items():
        for state in states:
            cw_rows.append(
                {
                    "energy_ev": state.energy_ev,
                    "intensity_w_cm2": intensity,
                    "paper_work_loss_cm2": state.paper_work_loss_cm2,
                    "excited_population": state.excited_population,
                    "inversion": state.inversion,
                    "root_count": state.root_count,
                    "max_periodic_bloch_radius": state.max_periodic_bloch_radius,
                }
            )
    _write_csv(output_dir / "figure2_cw_spectra.csv", cw_rows)
    intensity_values = np.logspace(-2.0, 7.0, intensity_points)
    intensity_rows = []
    previous = None
    for intensity in intensity_values:
        state = solve_cw_harmonic_state(
            model,
            energy_ev=profile.transition_energy_ev,
            intensity_w_cm2=float(intensity),
            response=response,
            preferred_inversion=previous,
        )
        previous = state.inversion
        intensity_rows.append(
            {
                "intensity_w_cm2": float(intensity),
                "paper_work_loss_cm2": state.paper_work_loss_cm2,
                "excited_population": state.excited_population,
                "inversion": state.inversion,
                "root_count": state.root_count,
            }
        )
    _write_csv(output_dir / "figure2_intensity_sweep.csv", intensity_rows)
    _plot_figure2(
        energies,
        cw_spectra,
        intensity_rows,
        output_dir / "figure2_native_dimer.png",
    )

    highlighted_traces: dict[float, PulseEnvelopeTrace] = {}
    highlighted_spectra: dict[float, np.ndarray] = {}
    for fluence in profile.pulse_fluences_j_cm2:
        if verbose:
            print(f"Pulse trace: {fluence:.6g} J/cm^2")
        trace = solve_pulse_envelope_trace(model, profile, fluence)
        highlighted_traces[fluence] = trace
        highlighted_spectra[fluence] = pulse_envelope_work_loss_spectrum_cm2(
            trace,
            profile,
            energies,
        )
    pulse_spectrum_rows = []
    for fluence, values in highlighted_spectra.items():
        for energy, value in zip(energies, values):
            pulse_spectrum_rows.append(
                {
                    "energy_ev": float(energy),
                    "fluence_j_cm2": fluence,
                    "paper_work_loss_cm2": float(value),
                }
            )
    _write_csv(output_dir / "figure3_pulse_spectra.csv", pulse_spectrum_rows)

    fluence_values = np.unique(
        np.concatenate(
            [
                np.logspace(-10.0, -4.0, fluence_points),
                np.asarray(profile.pulse_fluences_j_cm2),
            ]
        )
    )
    fluence_results: list[tuple[float, float, PulseEnvelopeTrace]] = []
    for index, fluence in enumerate(fluence_values, start=1):
        trace = highlighted_traces.get(float(fluence))
        if trace is None:
            if verbose:
                print(f"Fluence sweep {index}/{len(fluence_values)}: {fluence:.6g}")
            trace = solve_pulse_envelope_trace(model, profile, float(fluence))
        value = float(
            pulse_envelope_work_loss_spectrum_cm2(
                trace,
                profile,
                np.asarray([profile.transition_energy_ev]),
            )[0]
        )
        fluence_results.append((float(fluence), value, trace))
    sweep_cross_section = np.asarray([item[1] for item in fluence_results])
    sweep_span = float(np.ptp(sweep_cross_section))
    peak_prominence = max(1e-3 * sweep_span, np.finfo(float).tiny)
    peaks, _ = find_peaks(
        sweep_cross_section,
        prominence=peak_prominence,
    )
    if peaks.size:
        first_fluence_peak = fluence_results[int(peaks[0])][0]
        pulse_area_reference = first_fluence_peak
    else:
        first_fluence_peak = None
        pulse_area_reference = np.nan
    fluence_rows = []
    for fluence, value, trace in fluence_results:
        operational_area = 2.0 * np.pi * np.sqrt(
            fluence / pulse_area_reference
        )
        fluence_rows.append(
            {
                "fluence_j_cm2": fluence,
                "resonant_paper_work_loss_cm2": value,
                "operational_pulse_area": float(operational_area),
                "max_bloch_radius": trace.max_bloch_radius,
                "min_density_eigenvalue": trace.min_density_eigenvalue,
                "tail_ratio": trace.tail_ratio,
                "solver_nfev": trace.solver_nfev,
            }
        )
    _write_csv(output_dir / "figure3_fluence_sweep.csv", fluence_rows)
    _plot_figure3(
        energies,
        highlighted_spectra,
        fluence_rows,
        output_dir / "figure3_native_dimer.png",
    )

    figure4_traces = {
        fluence: highlighted_traces[fluence]
        for fluence in (5.0e-9, 5.0e-7)
    }
    dynamics_rows = []
    for fluence, trace in figure4_traces.items():
        modal, P, Q, W = _unpack_envelope_state(trace.state, model.n_modes)
        for index in range(trace.t_au.size):
            dynamics_rows.append(
                {
                    "fluence_j_cm2": fluence,
                    "time_fs": float(au_to_fs(trace.t_au[index])),
                    "field_envelope_v_m": float(
                        field_au_to_si(abs(trace.field_envelope_au[index]))
                    ),
                    "excited_population": float(0.5 * (W[index] + 1.0)),
                    "bloch_W": float(W[index]),
                    "bloch_Q_envelope_real": float(Q[index].real),
                    "bloch_Q_envelope_imag": float(Q[index].imag),
                    "bloch_P_envelope_real": float(P[index].real),
                    "bloch_P_envelope_imag": float(P[index].imag),
                    "qd_dipole_envelope_abs_debye": float(
                        abs(trace.qd_envelope_au[index])
                        * AU_DIPOLE_C_M
                        / DEBYE_C_M
                    ),
                    "dimer_dipole_envelope_abs_debye": float(
                        2.0
                        * abs(trace.each_mnp_envelope_au[index])
                        * AU_DIPOLE_C_M
                        / DEBYE_C_M
                    ),
                }
            )
    _write_csv(output_dir / "figure4_dynamics.csv", dynamics_rows)
    _plot_figure4(figure4_traces, output_dir / "figure4_native_dimer.png")

    audit_energies = np.linspace(1.94, 2.14, 2001)
    modal_single = model.C * model.alpha_single_dimless(
        audit_energies,
        response="modal",
    )
    material_single = model.C * model.alpha_single_dimless(
        audit_energies,
        response="material",
    )
    modal_dimer = model.alpha_bare_dimer_au(audit_energies, response="modal")
    material_dimer = model.alpha_bare_dimer_au(
        audit_energies,
        response="material",
    )
    local_single_error = float(
        np.max(np.abs(modal_single - material_single))
        / max(float(np.max(np.abs(material_single))), np.finfo(float).tiny)
    )
    local_dimer_error = float(
        np.max(np.abs(modal_dimer - material_dimer))
        / max(float(np.max(np.abs(material_dimer))), np.finfo(float).tiny)
    )
    linear_min_index = _nearest_local_extremum_index(
        energies,
        linear_work,
        center_ev=profile.transition_energy_ev,
        kind="minimum",
    )
    linear_peak_index = _nearest_local_extremum_index(
        energies,
        linear_work,
        center_ev=profile.transition_energy_ev,
        kind="maximum",
    )
    bare_at_resonance = float(
        np.interp(profile.transition_energy_ev, energies, bare_work)
    )
    pulse_max_index = int(np.nanargmax(sweep_cross_section))
    pulse_peak_at_resonance = float(sweep_cross_section[pulse_max_index])
    weak_pulse_at_resonance = float(sweep_cross_section[0])
    response_low_intensity = float(intensity_rows[0]["paper_work_loss_cm2"])
    response_high_intensity = float(intensity_rows[-1]["paper_work_loss_cm2"])
    response_half = 0.5 * (response_low_intensity + response_high_intensity)
    half_response_index = int(
        np.argmin(
            np.abs(
                np.asarray([row["paper_work_loss_cm2"] for row in intensity_rows])
                - response_half
            )
        )
    )
    metadata = {
        "comparison": "Shah 2013 using the current native symmetric-dimer model",
        "citation": "R. A. Shah et al., Phys. Rev. B 88, 075411 (2013)",
        "doi": "10.1103/PhysRevB.88.075411",
        "article_pdf": str(article_pdf),
        "article_pdf_sha256": _article_pdf_hash(article_pdf),
        "model_branch": "native two-ellipsoid quasistatic dipole model, symmetric bright sector",
        "pulse_solver": "rotating-wave envelope of the same native modal/Bloch equations",
        "linear_and_cw_response": response,
        "pulse_response": "modal",
        "decay_profile": decay_profile,
        "geometry": {
            "two_identical_Au_prolate_spheroids": True,
            "mnp_semimajor_nm": profile.mnp_semimajor_nm,
            "mnp_semiminor_nm": profile.mnp_semiminor_nm,
            "mnp_surface_gap_nm": profile.mnp_surface_gap_nm,
            "mnp_center_distance_nm": profile.mnp_center_distance_nm,
            "qd_radius_nm": profile.qd_radius_nm,
            "qd_to_each_mnp_center_nm": profile.qd_to_mnp_center_nm,
            "qd_to_each_mnp_surface_gap_nm": profile.qd_mnp_surface_gap_nm,
            "c_over_R": profile.mnp_semimajor_nm / profile.qd_to_mnp_center_nm,
            "explicit_full_state_dimension": 4 * model.n_modes + 3,
            "symmetric_reduced_state_dimension": 2 * model.n_modes + 3,
        },
        "paper_effective_mode_not_assigned_to_each_native_mnp": {
            "d_s_debye": profile.effective_dimer_dipole_debye,
            "gamma_s_mev": profile.plasmon_linewidth_mev,
            "g_mev": profile.coupling_g_mev,
            "reason": "These are DDA-fitted constants of the whole dimer bright mode.",
        },
        "density_matrix_rates_mev": {
            "free_population_gamma1": profile.qd_free_population_decay_mev,
            "thermal_pure_dephasing": profile.qd_thermal_dephasing_mev,
            "paper_effective_population_gamma1_computed": profile.effective_population_decay_mev,
            "paper_corrected_sc_coherence_damping": profile.qd_thermal_dephasing_mev,
            "paper_corrected_sc_is_cp": bool(
                profile.qd_thermal_dephasing_mev
                >= 0.5 * profile.effective_population_decay_mev
            ),
            "selected_gamma1": float(au_to_eV(model.params.gamma_au) * 1000.0),
            "selected_total_Gamma2": gamma2_mev,
            "selected_pure_dephasing": float(
                au_to_eV(model.params.pure_dephasing_au) * 1000.0
            ),
        },
        "modal_fit": {
            "n_modes_per_mnp": model.n_modes,
            "fit_window_ev": list(model.fit_window_ev),
            "provenance": model.fit_provenance,
            **_SHAH_N10_FIT_METRICS,
            "local_1p94_2p14_single_alpha_normalized_max_error": local_single_error,
            "local_1p94_2p14_dimer_alpha_normalized_max_error": local_dimer_error,
            "single_modal_min_imag": float(np.min(modal_single.imag)),
            "dimer_modal_min_imag": float(np.min(modal_dimer.imag)),
        },
        "couplings_atomic_units": {
            "J_qd_to_each_mnp": model.J,
            "K_mnp_to_mnp": model.K,
        },
        "stability": {
            "symmetric_stable": model.stability.symmetric_stable,
            "antisymmetric_stable": model.stability.antisymmetric_stable,
            "symmetric_spectral_abscissa_au": float(
                np.max(model.stability.symmetric_poles_au.real)
            ),
            "antisymmetric_spectral_abscissa_au": float(
                np.max(model.stability.antisymmetric_poles_au.real)
            ),
        },
        "grids": {
            "energy_points": energy_points,
            "energy_step_mev": energy_step_mev,
            "Gamma2_over_4_mev": gamma2_mev / 4.0,
            "intensity_points": intensity_points,
            "fluence_points_plus_highlights": len(fluence_results),
            "pulse_positive_frequency_fit_window_fraction": float(
                pulse_from_fluence(
                    profile,
                    profile.pulse_fluences_j_cm2[0],
                ).positive_frequency_spectral_fraction(model.fit_window_ev)
            ),
        },
        "computed_metrics": {
            "linear_fano_local_min_found": linear_min_index is not None,
            "linear_fano_min_energy_ev": (
                None
                if linear_min_index is None
                else float(energies[linear_min_index])
            ),
            "linear_fano_min_work_loss_cm2": (
                None
                if linear_min_index is None
                else float(linear_work[linear_min_index])
            ),
            "linear_fano_local_peak_found": linear_peak_index is not None,
            "linear_fano_peak_energy_ev": (
                None
                if linear_peak_index is None
                else float(energies[linear_peak_index])
            ),
            "linear_fano_peak_work_loss_cm2": (
                None
                if linear_peak_index is None
                else float(linear_work[linear_peak_index])
            ),
            "bare_dimer_work_loss_at_2p042_ev_cm2": bare_at_resonance,
            "operational_cw_half_response_intensity_w_cm2": float(
                intensity_rows[half_response_index]["intensity_w_cm2"]
            ),
            "first_resonant_fluence_peak_j_cm2": first_fluence_peak,
            "pulse_area_reference_is_first_resonant_fluence_peak": bool(
                first_fluence_peak is not None
            ),
            "maximum_pulse_resonant_work_loss_cm2": pulse_peak_at_resonance,
            "fluence_at_maximum_resonant_work_loss_j_cm2": float(
                fluence_results[pulse_max_index][0]
            ),
            "maximum_resonant_response_over_bare_fraction": (
                pulse_peak_at_resonance / bare_at_resonance - 1.0
            ),
            "weakest_fluence_resonant_response_over_bare_fraction": (
                weak_pulse_at_resonance / bare_at_resonance - 1.0
            ),
            "maximum_pulse_bloch_radius": float(
                max(trace.max_bloch_radius for _, _, trace in fluence_results)
            ),
            "minimum_pulse_density_eigenvalue": float(
                min(trace.min_density_eigenvalue for _, _, trace in fluence_results)
            ),
            "maximum_pulse_tail_ratio": float(
                max(trace.tail_ratio for _, _, trace in fluence_results)
            ),
            "figure4_max_excited_population_by_fluence_j_cm2": {
                f"{fluence:.12g}": float(
                    np.max(0.5 * (trace.inversion + 1.0))
                )
                for fluence, trace in figure4_traces.items()
            },
        },
        "paper_targets_not_digitized": {
            "fano_center_ev": 2.042,
            "corrected_sc_saturation_intensity_w_cm2_approximately": 3.0e4,
            "reversal_fluence_j_cm2_approximately": 5.0e-7,
            "maximum_enhancement_over_bare_approximately": 0.08,
        },
        "terminology": (
            "The plotted k*Im(alpha)/epsilon0 follows the paper's sigma_abs label; "
            "the project records it as quasistatic work loss, not strict material absorption."
        ),
        "limitations": [
            (
                "No DDA solver or digitized article curves are included, "
                "so no pointwise RMSE is claimed."
            ),
            (
                "At c/R=15/18 the explicit point-dipole dimer is outside "
                "the project's conservative c/R<=0.3 guide."
            ),
            (
                "The native model omits a geometry-derived Purcell channel; "
                "purcell_cp imports the paper's effective gamma1 "
                "phenomenologically."
            ),
            (
                "The paper's raw corrected-SC gamma pair is rejected because "
                "it is not CP/Lindblad compatible."
            ),
            (
                "Figure 4 in the paper is CQED; this output is the project's "
                "semiclassical density-matrix trajectory."
            ),
        ],
        "native_parameters": params_to_physical_dict(model.params, "long"),
    }
    with (output_dir / "comparison_metadata.json").open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)
    return metadata


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build native symmetric-dimer counterparts of Shah et al. "
            "Phys. Rev. B 88, 075411 (2013), figures 1--4."
        )
    )
    parser.add_argument(
        "--article-pdf",
        type=Path,
        default=Path("articles/shah2013.pdf"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/shah2013_native_dimer"),
    )
    parser.add_argument(
        "--decay-profile",
        choices=["naive", "purcell_cp"],
        default="purcell_cp",
    )
    parser.add_argument(
        "--response",
        choices=["modal", "material"],
        default="modal",
    )
    parser.add_argument(
        "--refit",
        action="store_true",
        help="Regenerate the cached N=10 response with HybridQDPlasmonModel.",
    )
    # 0.25 meV spacing resolves Gamma2/4 for both supported decay profiles.
    parser.add_argument("--energy-points", type=int, default=801)
    parser.add_argument("--intensity-points", type=int, default=81)
    parser.add_argument("--fluence-points", type=int, default=41)
    parser.add_argument("--quiet", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metadata = run_comparison(
        profile=Shah2013Profile(),
        output_dir=args.output_dir,
        article_pdf=args.article_pdf,
        decay_profile=args.decay_profile,
        response=args.response,
        refit=args.refit,
        energy_points=args.energy_points,
        intensity_points=args.intensity_points,
        fluence_points=args.fluence_points,
        verbose=not args.quiet,
    )
    metrics = metadata["computed_metrics"]
    print(f"Wrote Shah native-dimer artifacts to {args.output_dir}")
    if metrics["linear_fano_local_min_found"]:
        fano_message = (
            "local Fano minimum "
            f"{metrics['linear_fano_min_energy_ev']:.6g} eV"
        )
    else:
        fano_message = "no local Fano minimum in the transition window"
    first_peak = metrics["first_resonant_fluence_peak_j_cm2"]
    if first_peak is None:
        fluence_message = "no resolved resonant fluence peak"
    else:
        fluence_message = f"first resonant fluence peak {first_peak:.6g} J/cm^2"
    print(
        f"Native result: {fano_message}; {fluence_message}."
    )
    print(
        "This is a native point-dipole comparison, not a DDA/CQED replication; "
        "inspect comparison_metadata.json before physical interpretation."
    )


if __name__ == "__main__":
    main()
