"""Native-model comparison with Sadeghi, Nanotechnology 20, 225401 (2009).

Sadeghi considers one spherical metallic nanoparticle (MNP) and one
two-level quantum dot (QD), aligned with the incident polarization.  This is
the spherical, longitudinal ``G=2`` limit of ``qd_mnp_rational_fit.py``.

The article works in the rotating-wave approximation (RWA), eliminates the
MNP adiabatically and follows nanosecond dynamics.  Calling the native
carrier-resolved solver for several nanoseconds would resolve millions of
optical periods.  The adapter below therefore evaluates the *same passive
modal polarizability* at the laser carrier and integrates the resulting RWA
density-matrix equations.  The mathematical core is not modified.

For the paper-convention coherence ``s=rho_21`` used here, define
``Omega=-Omega_paper`` so that the printed negative bare coupling becomes a
positive drive magnitude.  The equations are

    Omega = Omega0(t) * (1 + J*alpha) + eta*s,
    eta   = d**2 * l_QD**2 * J**2 * alpha,
    dot p = 2 Im(Omega.conj()*s) - gamma1*p,
    dot s = -(Gamma2 + i*Delta)*s + i*Omega*(1 - 2*p),

where ``p=rho_22``, ``J=2/(eps_h*R**3)`` and ``alpha`` is the physical MNP
polarizability from the project.  These equations are the adiabatic RWA limit
of the native Bloch/modal equations: the plasmon coordinates have been
eliminated after evaluating their passive modal response at the carrier.

The PDF does not state the numerical MNP radius, host/QD permittivities,
transition energy or metal data.  The commonly used values below are
reconstructed from the model cited as reference 9 by Sadeghi.  They are kept
separate from constants printed directly in the article.  The project also
uses Johnson--Christy Au data, whereas the cited source used Palik; exact
pixel-level reproduction is therefore neither claimed nor expected.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Literal

import matplotlib.pyplot as plt
import numpy as np
from scipy.constants import c as C_SI, e as E_CHARGE, epsilon_0, hbar
from scipy.integrate import solve_ivp
from scipy.optimize import least_squares, root

from qd_mnp_params import make_params_with_overrides
from qd_mnp_rational_fit import (
    AU_TIME_S,
    DEBYE_C_M,
    HybridQDPlasmonModel,
    HybridSystemParams,
    RationalLorentzFit,
    eV_to_au,
    nm_to_au,
    params_to_physical_dict,
)


MNPResponse = Literal["modal", "material"]
MEV_TO_NS_INV = 1.0e-3 * E_CHARGE / hbar * 1.0e-9
MAX_DETUNING_STEP_FRACTION_OF_GAMMA2 = 0.25
_SADEGHI_PLOT_ARTIFACTS = (
    "figure_2_population.png",
    "figure_3_rabi_and_rate.png",
    "figure_4_rabi_and_rate.png",
    "figure_5_switch_on_rabi_and_rate.png",
    "figure_6_resonant_population.png",
    "figure_7_detuned_population.png",
)


# Deterministic N=9 fit generated by HybridQDPlasmonModel for the reconstructed
# 7.5 nm Au sphere in vacuum on 0.8--3.0 eV.  It is a cache of the current
# fitter, not a second material model.  ``--refit`` regenerates it.
_SADEGHI_N9_ALPHA_INF = 0.0
_SADEGHI_N9_STRENGTHS_AU2 = np.asarray(
    [
        0.0006558314181888231,
        0.0008929842956135423,
        0.0006870200161360804,
        0.0007967970353633371,
        0.0009322542169155941,
        0.0013675627029211951,
        3.9620915396416634e-09,
        4.1347533731346126e-07,
        0.14427781953561658,
    ],
    dtype=float,
)
_SADEGHI_N9_OMEGA_EV = np.asarray(
    [
        2.363246803405168,
        2.460924943216109,
        2.5941246257253345,
        2.7562749026736593,
        2.932235626109125,
        3.1119093219644975,
        4.852660982951309,
        5.399026687420555,
        6.599999999600051,
    ],
    dtype=float,
)
_SADEGHI_N9_GAMMA_EV = np.asarray(
    [
        0.19632770137568484,
        0.18351039017657494,
        0.2206066789484803,
        0.26269252667992604,
        0.2629495248171712,
        0.11503849657854129,
        0.01765437130575733,
        0.013393492297617706,
        0.008000000000000021,
    ],
    dtype=float,
)
def _rate_au_to_ns_inv(value: complex | np.ndarray) -> complex | np.ndarray:
    return np.asarray(value) / AU_TIME_S * 1.0e-9


def _rate_ns_inv_to_mev(value: float) -> float:
    return float(value / MEV_TO_NS_INV)


def _dipole_enm_to_debye(value: float) -> float:
    return float(value * E_CHARGE * 1.0e-9 / DEBYE_C_M)


@dataclass(frozen=True)
class Sadeghi2009Profile:
    """Article constants plus an explicitly identified reconstructed profile."""

    # Printed directly in Sadeghi 2009.
    transition_dipole_e_nm: float = 0.65
    population_lifetime_ns: float = 0.8
    coherence_decay_ns_inv: float = 2.7
    weak_intensity_w_cm2: float = 1.0
    strong_intensity_w_cm2: float = 1.0e3
    distances_nm: tuple[float, ...] = (100.0, 20.0, 17.0, 15.0)

    # Reconstructed from the Zhang--Govorov--Bryant model cited by Sadeghi.
    sphere_radius_nm: float = 7.5
    eps_environment: float = 1.0
    eps_qd: float = 6.0
    transition_energy_ev: float = 2.5
    qd_radius_nm: float = 0.0

    # The exact ramp is not printed; this is an explicit project assumption.
    switch_center_ns: float = 10.0
    switch_rise_10_90_ns: float = 0.4
    time_start_ns: float = 8.5
    time_end_ns: float = 13.0

    def __post_init__(self) -> None:
        values = np.asarray(
            [
                self.transition_dipole_e_nm,
                self.population_lifetime_ns,
                self.coherence_decay_ns_inv,
                self.weak_intensity_w_cm2,
                self.strong_intensity_w_cm2,
                self.sphere_radius_nm,
                self.eps_environment,
                self.eps_qd,
                self.transition_energy_ev,
                self.switch_rise_10_90_ns,
            ],
            dtype=float,
        )
        if np.any(~np.isfinite(values)) or np.any(values <= 0.0):
            raise ValueError("All positive Sadeghi profile constants must be finite.")
        if not np.isfinite(self.qd_radius_nm) or self.qd_radius_nm < 0.0:
            raise ValueError("qd_radius_nm must be finite and non-negative.")
        if self.time_end_ns <= self.time_start_ns:
            raise ValueError("time_end_ns must be greater than time_start_ns.")
        if len(self.distances_nm) == 0 or any(
            not np.isfinite(value) or value <= 0.0
            for value in self.distances_nm
        ):
            raise ValueError("distances_nm must contain positive finite values.")
        if min(self.surface_gap_nm(value) for value in self.distances_nm) <= 0.0:
            raise ValueError("Every Sadeghi geometry must have a positive surface gap.")
        if self.coherence_decay_ns_inv < 0.5 * self.population_decay_ns_inv:
            raise ValueError("The profile must satisfy Gamma2 >= gamma1/2.")

    @property
    def population_decay_ns_inv(self) -> float:
        return 1.0 / self.population_lifetime_ns

    @property
    def pure_dephasing_ns_inv(self) -> float:
        return self.coherence_decay_ns_inv - 0.5 * self.population_decay_ns_inv

    @property
    def transition_dipole_debye(self) -> float:
        return _dipole_enm_to_debye(self.transition_dipole_e_nm)

    @property
    def qd_local_field_factor(self) -> float:
        return 3.0 * self.eps_environment / (
            self.eps_qd + 2.0 * self.eps_environment
        )

    @property
    def epsilon_eff1(self) -> float:
        return 1.0 / self.qd_local_field_factor

    def surface_gap_nm(self, distance_nm: float) -> float:
        return float(distance_nm - self.sphere_radius_nm - self.qd_radius_nm)

    def field_amplitude_v_m(self, intensity_w_cm2: float) -> float:
        """Return the real-field peak using the project's host normalization."""

        if not np.isfinite(intensity_w_cm2) or intensity_w_cm2 < 0.0:
            raise ValueError("intensity_w_cm2 must be finite and non-negative.")
        refractive_index = np.sqrt(self.eps_environment)
        return float(
            np.sqrt(
                2.0
                * intensity_w_cm2
                * 1.0e4
                / (refractive_index * epsilon_0 * C_SI)
            )
        )

    def isolated_rabi_ns_inv(self, intensity_w_cm2: float) -> float:
        """Article's half-Rabi coupling |mu E0|/(2 hbar eps_eff1)."""

        dipole_si = self.transition_dipole_e_nm * E_CHARGE * 1.0e-9
        omega_s_inv = (
            dipole_si
            * self.qd_local_field_factor
            * self.field_amplitude_v_m(intensity_w_cm2)
            / (2.0 * hbar)
        )
        return float(omega_s_inv * 1.0e-9)

    def provenance(self) -> dict[str, object]:
        return {
            "direct_from_sadeghi2009": {
                "transition_dipole_e_nm": self.transition_dipole_e_nm,
                "population_lifetime_ns": self.population_lifetime_ns,
                "coherence_decay_ns_inv": self.coherence_decay_ns_inv,
                "weak_intensity_w_cm2": self.weak_intensity_w_cm2,
                "strong_intensity_w_cm2": self.strong_intensity_w_cm2,
                "distances_nm": list(self.distances_nm),
            },
            "inferred_from_sadeghi_reference_9": {
                "sphere_radius_nm": self.sphere_radius_nm,
                "eps_environment": self.eps_environment,
                "eps_qd": self.eps_qd,
                "transition_energy_ev": self.transition_energy_ev,
            },
            "project_model_choices": {
                "gold_data": "Johnson-Christy table bundled with the project",
                "paper_reference_gold_data": "Palik",
                "qd_radius_nm": self.qd_radius_nm,
                "qd_geometry_reason": (
                    "point-QD because neither Sadeghi nor its reference-9 "
                    "parameter list specifies a QD radius for this calculation"
                ),
                "switch_on": (
                    "logistic amplitude ramp with the stated 10--90 percent "
                    "rise time; exact article ramp is unavailable"
                ),
                "ground_state_decay_gamma11": 0.0,
            },
        }


def build_sadeghi_params(profile: Sadeghi2009Profile) -> HybridSystemParams:
    """Create a core-compatible parameter record for the closest geometry."""

    closest_distance = min(profile.distances_nm)
    return make_params_with_overrides(
        c_nm=profile.sphere_radius_nm,
        a_nm=profile.sphere_radius_nm,
        r_nm=closest_distance,
        qd_radius_nm=profile.qd_radius_nm,
        eps_m=profile.eps_environment,
        eps_qd=profile.eps_qd,
        d_debye=profile.transition_dipole_debye,
        omega0_ev=profile.transition_energy_ev,
        gamma_population_mev=_rate_ns_inv_to_mev(
            profile.population_decay_ns_inv
        ),
        gamma2_coherence_mev=_rate_ns_inv_to_mev(
            profile.coherence_decay_ns_inv
        ),
        orientation="long",
        qd_dipole_convention="bare_internal",
    )


def _sphere_material_alpha_dimless(
    params: HybridSystemParams,
    energies_ev: float | np.ndarray,
) -> np.ndarray:
    epsilon_gold = params.material.epsilon_at(energies_ev)
    contrast = epsilon_gold - params.eps_m
    return np.asarray(
        contrast / (params.eps_m + contrast / 3.0),
        dtype=complex,
    )


def _modal_alpha_dimless(
    fit: RationalLorentzFit,
    energies_ev: float | np.ndarray,
) -> np.ndarray:
    omega = np.asarray(eV_to_au(energies_ev), dtype=float)
    alpha = np.full_like(omega, fit.alpha_inf, dtype=complex)
    for strength, mode_omega, mode_gamma in zip(
        fit.strengths_au2,
        fit.omega_modes_au,
        fit.gamma_modes_au,
    ):
        alpha += strength / (
            mode_omega**2 - omega**2 - 1j * mode_gamma * omega
        )
    return alpha


def _cached_sadeghi_fit(params: HybridSystemParams) -> RationalLorentzFit:
    mask = (
        (params.material.energy_eV >= 0.8)
        & (params.material.energy_eV <= 3.0)
    )
    dense_energies = np.linspace(0.8, 3.0, max(1025, 256 * 9))
    energies = np.unique(
        np.concatenate(
            ([0.8, 3.0], dense_energies, params.material.energy_eV[mask])
        )
    )
    target = _sphere_material_alpha_dimless(params, energies)
    omega = np.asarray(eV_to_au(energies), dtype=float)
    fitted = np.full_like(omega, _SADEGHI_N9_ALPHA_INF, dtype=complex)
    for strength, mode_energy, mode_gamma in zip(
        _SADEGHI_N9_STRENGTHS_AU2,
        _SADEGHI_N9_OMEGA_EV,
        _SADEGHI_N9_GAMMA_EV,
    ):
        mode_omega_au = float(eV_to_au(mode_energy))
        mode_gamma_au = float(eV_to_au(mode_gamma))
        fitted += strength / (
            mode_omega_au**2 - omega**2 - 1j * mode_gamma_au * omega
        )
    inverse_target = 1.0 / target
    inverse_fitted = 1.0 / fitted
    alpha_error = fitted - target
    inverse_error = inverse_fitted - inverse_target
    rms_alpha = float(np.sqrt(np.mean(np.abs(alpha_error) ** 2)))
    rms_inverse = float(np.sqrt(np.mean(np.abs(inverse_error) ** 2)))
    normalized_rms_alpha = rms_alpha / float(
        np.sqrt(np.mean(np.abs(target) ** 2))
    )
    normalized_rms_inverse = rms_inverse / float(
        np.sqrt(np.mean(np.abs(inverse_target) ** 2))
    )
    max_normalized_error = float(np.max(np.abs(alpha_error) / np.abs(target)))
    residual_parts = [
        alpha_error.real / max(float(np.max(np.abs(target.real))), 1.0e-12),
        alpha_error.imag / max(float(np.max(np.abs(target.imag))), 1.0e-12),
        np.sqrt(1.2)
        * inverse_error.real
        / max(float(np.max(np.abs(inverse_target.real))), 1.0e-12),
        np.sqrt(1.2)
        * inverse_error.imag
        / max(float(np.max(np.abs(inverse_target.imag))), 1.0e-12),
    ]
    cached_score = float(np.sqrt(np.mean(np.concatenate(residual_parts) ** 2)))
    passivity_energies = np.linspace(0.8, 3.0, max(1024, 256 * 9))
    passivity_omega = np.asarray(eV_to_au(passivity_energies), dtype=float)
    passivity_alpha = np.full_like(
        passivity_omega,
        _SADEGHI_N9_ALPHA_INF,
        dtype=complex,
    )
    for strength, mode_energy, mode_gamma in zip(
        _SADEGHI_N9_STRENGTHS_AU2,
        _SADEGHI_N9_OMEGA_EV,
        _SADEGHI_N9_GAMMA_EV,
    ):
        mode_omega_au = float(eV_to_au(mode_energy))
        mode_gamma_au = float(eV_to_au(mode_gamma))
        passivity_alpha += strength / (
            mode_omega_au**2
            - passivity_omega**2
            - 1j * mode_gamma_au * passivity_omega
        )
    minimum_imaginary = float(np.min(passivity_alpha.imag))
    return RationalLorentzFit(
        alpha_inf=_SADEGHI_N9_ALPHA_INF,
        strengths_au2=_SADEGHI_N9_STRENGTHS_AU2,
        omega_modes_au=np.asarray(eV_to_au(_SADEGHI_N9_OMEGA_EV), dtype=float),
        gamma_modes_au=np.asarray(eV_to_au(_SADEGHI_N9_GAMMA_EV), dtype=float),
        energies_used_eV=energies,
        alpha_used=target,
        rms_alpha=rms_alpha,
        rms_inv_alpha=rms_inverse,
        cost=cached_score,
        normalized_rms_alpha=normalized_rms_alpha,
        normalized_rms_inv_alpha=normalized_rms_inverse,
        max_normalized_alpha_error=max_normalized_error,
        min_imag_alpha_fit_window=minimum_imaginary,
        passivity_grid_points=int(passivity_omega.size),
        passive_on_fit_window=True,
        passive_for_all_positive_frequencies=True,
    )


@dataclass(frozen=True)
class SadeghiCoupling:
    laser_energy_ev: float
    distance_nm: float
    alpha_mnp_au: complex
    direct_factor: complex
    feedback_ns_inv: complex
    point_qd_surface_gap_nm: float


class SadeghiRWAAdapter:
    """Adiabatic spherical ``G=2`` RWA limit of the unchanged native model."""

    fit_window_ev = (0.8, 3.0)

    def __init__(
        self,
        profile: Sadeghi2009Profile | None = None,
        *,
        fit: RationalLorentzFit | None = None,
    ) -> None:
        self.profile = profile or Sadeghi2009Profile()
        self.params = build_sadeghi_params(self.profile)
        self.fit = fit or _cached_sadeghi_fit(self.params)
        self.C = (
            self.params.eps_m
            * self.params.a_au**2
            * self.params.c_au
            / 3.0
        )

    def alpha_dimless(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> np.ndarray:
        energies = np.asarray(energies_ev, dtype=float)
        if np.any(~np.isfinite(energies)):
            raise ValueError("Requested energies must be finite.")
        if response == "modal":
            lo, hi = self.fit_window_ev
            if np.any(energies < lo) or np.any(energies > hi):
                raise ValueError("Modal response requested outside the 0.8--3.0 eV fit window.")
            return _modal_alpha_dimless(self.fit, energies)
        if response == "material":
            return _sphere_material_alpha_dimless(self.params, energies)
        raise ValueError("response must be 'modal' or 'material'.")

    def alpha_physical_au(
        self,
        energies_ev: float | np.ndarray,
        *,
        response: MNPResponse = "modal",
    ) -> np.ndarray:
        return self.C * self.alpha_dimless(energies_ev, response=response)

    def coupling(
        self,
        *,
        laser_energy_ev: float,
        distance_nm: float,
        response: MNPResponse = "modal",
    ) -> SadeghiCoupling:
        gap = self.profile.surface_gap_nm(distance_nm)
        if gap <= 0.0:
            raise ValueError("The point-QD surface gap must be strictly positive.")
        distance_au = float(nm_to_au(distance_nm))
        alpha = complex(self.alpha_physical_au(laser_energy_ev, response=response))
        J = 2.0 / (self.params.eps_m * distance_au**3)
        local = self.params.qd_local_field_factor
        eta_au = self.params.d_au**2 * local**2 * J**2 * alpha
        return SadeghiCoupling(
            laser_energy_ev=float(laser_energy_ev),
            distance_nm=float(distance_nm),
            alpha_mnp_au=alpha,
            direct_factor=complex(1.0 + J * alpha),
            feedback_ns_inv=complex(_rate_au_to_ns_inv(eta_au)),
            point_qd_surface_gap_nm=gap,
        )


def build_sadeghi_adapter(
    profile: Sadeghi2009Profile | None = None,
    *,
    refit: bool = False,
) -> SadeghiRWAAdapter:
    profile = profile or Sadeghi2009Profile()
    if not refit:
        return SadeghiRWAAdapter(profile)
    params = build_sadeghi_params(profile)
    core_model = HybridQDPlasmonModel(
        params,
        orientation="long",
        n_modes=9,
        fit_window_eV=(0.8, 3.0),
        radiative_consistency_policy="ignore",
        verbose=True,
    )
    return SadeghiRWAAdapter(profile, fit=core_model.fit)


@dataclass(frozen=True)
class SadeghiSteadyState:
    detuning_mev: float
    laser_energy_ev: float
    distance_nm: float
    intensity_w_cm2: float
    excited_population: float
    coherence_21: complex
    normalized_rabi_ns_inv: complex
    physical_excitation_ns_inv: float
    literal_paper_G_ns_inv: float
    negated_physical_excitation_ns_inv: float
    bloch_radius: float
    residual_norm: float
    max_jacobian_real_part_ns_inv: float
    locally_stable: bool
    solver_success: bool


def isolated_steady_state(
    *,
    omega_ns_inv: complex,
    detuning_ns_inv: float,
    gamma1_ns_inv: float,
    gamma2_ns_inv: float,
) -> tuple[float, complex]:
    """Analytic stationary state for an isolated coherently driven TLS."""

    denominator = gamma2_ns_inv**2 + detuning_ns_inv**2
    pumping = 2.0 * abs(omega_ns_inv) ** 2 * gamma2_ns_inv / denominator
    population = pumping / (gamma1_ns_inv + 2.0 * pumping)
    inversion_ground_minus_excited = 1.0 - 2.0 * population
    coherence = (
        1j
        * omega_ns_inv
        * inversion_ground_minus_excited
        / (gamma2_ns_inv + 1j * detuning_ns_inv)
    )
    return float(population), complex(coherence)


def _steady_residual(
    vector: np.ndarray,
    *,
    omega0_ns_inv: float,
    coupling: SadeghiCoupling,
    detuning_ns_inv: float,
    gamma1_ns_inv: float,
    gamma2_ns_inv: float,
) -> np.ndarray:
    population, coherence_real, coherence_imag = vector
    coherence = complex(coherence_real, coherence_imag)
    omega = omega0_ns_inv * coupling.direct_factor + coupling.feedback_ns_inv * coherence
    population_dot = (
        2.0 * np.imag(np.conj(omega) * coherence)
        - gamma1_ns_inv * population
    )
    coherence_dot = (
        -(gamma2_ns_inv + 1j * detuning_ns_inv) * coherence
        + 1j * omega * (1.0 - 2.0 * population)
    )
    scale = max(
        gamma1_ns_inv,
        gamma2_ns_inv,
        abs(detuning_ns_inv),
        abs(omega0_ns_inv),
        abs(coupling.feedback_ns_inv),
        1.0,
    )
    return np.asarray(
        [population_dot, coherence_dot.real, coherence_dot.imag],
        dtype=float,
    ) / scale


def steady_state_jacobian_ns_inv(
    *,
    population: float,
    coherence_21: complex,
    direct_drive_ns_inv: complex,
    feedback_ns_inv: complex,
    detuning_ns_inv: float,
    gamma1_ns_inv: float,
    gamma2_ns_inv: float,
) -> np.ndarray:
    """Jacobian of the physical RWA equations in ``(rho22, Re s, Im s)``."""

    x = float(coherence_21.real)
    y = float(coherence_21.imag)
    direct_real = float(direct_drive_ns_inv.real)
    direct_imag = float(direct_drive_ns_inv.imag)
    feedback_real = float(feedback_ns_inv.real)
    feedback_imag = float(feedback_ns_inv.imag)
    inversion = 1.0 - 2.0 * population
    omega_real = direct_real + feedback_real * x - feedback_imag * y
    omega_imag = direct_imag + feedback_imag * x + feedback_real * y
    return np.asarray(
        [
            [
                -gamma1_ns_inv,
                -2.0 * direct_imag - 4.0 * feedback_imag * x,
                2.0 * direct_real - 4.0 * feedback_imag * y,
            ],
            [
                2.0 * omega_imag,
                -gamma2_ns_inv - feedback_imag * inversion,
                detuning_ns_inv - feedback_real * inversion,
            ],
            [
                -2.0 * omega_real,
                -detuning_ns_inv + feedback_real * inversion,
                -gamma2_ns_inv - feedback_imag * inversion,
            ],
        ],
        dtype=float,
    )


def solve_steady_state(
    adapter: SadeghiRWAAdapter,
    *,
    detuning_mev: float,
    distance_nm: float,
    intensity_w_cm2: float,
    response: MNPResponse = "modal",
    initial_state: SadeghiSteadyState | None = None,
) -> SadeghiSteadyState:
    """Solve one converged, positive article-style RWA fixed point."""

    profile = adapter.profile
    laser_energy_ev = profile.transition_energy_ev - detuning_mev * 1.0e-3
    coupling = adapter.coupling(
        laser_energy_ev=laser_energy_ev,
        distance_nm=distance_nm,
        response=response,
    )
    detuning_ns_inv = detuning_mev * MEV_TO_NS_INV
    omega0 = profile.isolated_rabi_ns_inv(intensity_w_cm2)
    if initial_state is None:
        initial_population, initial_coherence = isolated_steady_state(
            omega_ns_inv=omega0 * coupling.direct_factor,
            detuning_ns_inv=detuning_ns_inv,
            gamma1_ns_inv=profile.population_decay_ns_inv,
            gamma2_ns_inv=profile.coherence_decay_ns_inv,
        )
        initial = np.asarray(
            [initial_population, initial_coherence.real, initial_coherence.imag],
            dtype=float,
        )
    else:
        initial = np.asarray(
            [
                initial_state.excited_population,
                initial_state.coherence_21.real,
                initial_state.coherence_21.imag,
            ],
            dtype=float,
        )

    result = least_squares(
        _steady_residual,
        initial,
        bounds=(np.asarray([0.0, -0.5, -0.5]), np.asarray([0.5, 0.5, 0.5])),
        args=(),
        kwargs={
            "omega0_ns_inv": omega0,
            "coupling": coupling,
            "detuning_ns_inv": detuning_ns_inv,
            "gamma1_ns_inv": profile.population_decay_ns_inv,
            "gamma2_ns_inv": profile.coherence_decay_ns_inv,
        },
        xtol=1.0e-13,
        ftol=1.0e-13,
        gtol=1.0e-13,
        max_nfev=3000,
    )
    solution_vector = np.asarray(result.x, dtype=float)
    bounded_residual = float(
        np.linalg.norm(
            _steady_residual(
                solution_vector,
                omega0_ns_inv=omega0,
                coupling=coupling,
                detuning_ns_inv=detuning_ns_inv,
                gamma1_ns_inv=profile.population_decay_ns_inv,
                gamma2_ns_inv=profile.coherence_decay_ns_inv,
            )
        )
    )
    # On the far-detuned tails rho22 can be so close to the lower bound that
    # the bounded optimizer terminates by projected-gradient tolerance before
    # driving all equations to machine precision.  One local Newton polishing
    # step removes that harmless active-bound residual; the physical domain is
    # checked again below.
    if bounded_residual > 1.0e-10:
        polished = root(
            lambda vector: _steady_residual(
                vector,
                omega0_ns_inv=omega0,
                coupling=coupling,
                detuning_ns_inv=detuning_ns_inv,
                gamma1_ns_inv=profile.population_decay_ns_inv,
                gamma2_ns_inv=profile.coherence_decay_ns_inv,
            ),
            solution_vector,
            method="hybr",
            options={"xtol": 1.0e-11, "maxfev": 2000},
        )
        polished_residual = float(
            np.linalg.norm(
                _steady_residual(
                    polished.x,
                    omega0_ns_inv=omega0,
                    coupling=coupling,
                    detuning_ns_inv=detuning_ns_inv,
                    gamma1_ns_inv=profile.population_decay_ns_inv,
                    gamma2_ns_inv=profile.coherence_decay_ns_inv,
                )
            )
        )
        if polished_residual < bounded_residual:
            solution_vector = np.asarray(polished.x, dtype=float)

    population = float(solution_vector[0])
    coherence = complex(solution_vector[1], solution_vector[2])
    omega = omega0 * coupling.direct_factor + coupling.feedback_ns_inv * coherence
    excitation = float(2.0 * np.imag(np.conj(omega) * coherence))
    bloch_radius = float(
        np.sqrt((1.0 - 2.0 * population) ** 2 + 4.0 * abs(coherence) ** 2)
    )
    residual_norm = float(
        np.linalg.norm(
            _steady_residual(
                solution_vector,
                omega0_ns_inv=omega0,
                coupling=coupling,
                detuning_ns_inv=detuning_ns_inv,
                gamma1_ns_inv=profile.population_decay_ns_inv,
                gamma2_ns_inv=profile.coherence_decay_ns_inv,
            )
        )
    )
    # The residual is already divided by the largest optical/RWA rate.  A
    # 1e-8 dimensionless gate is far below the accuracy visible in any saved
    # observable, while avoiding false failures when a bounded solution sits
    # close to rho22=0 on the far-detuned tails.
    success = bool(residual_norm <= 1.0e-8)
    if not success:
        raise RuntimeError(
            "Sadeghi steady-state solve did not converge: "
            f"message={result.message!s}, residual={residual_norm:.6g}."
        )
    if population < -2.0e-10 or population > 0.5 + 2.0e-8:
        raise RuntimeError(
            "The stationary population lies outside the passive CW interval: "
            f"rho22={population:.9g}."
        )
    population = float(np.clip(population, 0.0, 0.5))
    if bloch_radius > 1.0 + 2.0e-7:
        raise RuntimeError(
            "The stationary density matrix is not positive: "
            f"Bloch radius={bloch_radius:.9g}."
        )
    jacobian = steady_state_jacobian_ns_inv(
        population=population,
        coherence_21=coherence,
        direct_drive_ns_inv=omega0 * coupling.direct_factor,
        feedback_ns_inv=coupling.feedback_ns_inv,
        detuning_ns_inv=detuning_ns_inv,
        gamma1_ns_inv=profile.population_decay_ns_inv,
        gamma2_ns_inv=profile.coherence_decay_ns_inv,
    )
    maximum_jacobian_real_part = float(
        np.max(np.linalg.eigvals(jacobian).real)
    )
    locally_stable = bool(maximum_jacobian_real_part < 0.0)
    if not locally_stable:
        raise RuntimeError(
            "The converged Sadeghi fixed point is locally unstable: "
            f"max Re(lambda)={maximum_jacobian_real_part:.9g} ns^-1."
        )
    return SadeghiSteadyState(
        detuning_mev=float(detuning_mev),
        laser_energy_ev=float(laser_energy_ev),
        distance_nm=float(distance_nm),
        intensity_w_cm2=float(intensity_w_cm2),
        excited_population=population,
        coherence_21=coherence,
        normalized_rabi_ns_inv=complex(omega),
        physical_excitation_ns_inv=excitation,
        # With Omega_script=-Omega_paper, the expression printed by Sadeghi is
        # 2 Im(Omega_paper*rho21) = -2 Im(Omega_script*rho21).  For a complex
        # Omega this is not identically the negative of the Hermitian physical
        # pumping term 2 Im(conj(Omega_script)*rho21), so both are retained.
        literal_paper_G_ns_inv=float(-2.0 * np.imag(omega * coherence)),
        negated_physical_excitation_ns_inv=-excitation,
        bloch_radius=bloch_radius,
        residual_norm=residual_norm,
        max_jacobian_real_part_ns_inv=maximum_jacobian_real_part,
        locally_stable=locally_stable,
        solver_success=success,
    )


def solve_steady_sweep(
    adapter: SadeghiRWAAdapter,
    detunings_mev: Iterable[float],
    *,
    distance_nm: float,
    intensity_w_cm2: float,
    response: MNPResponse = "modal",
) -> list[SadeghiSteadyState]:
    states: list[SadeghiSteadyState] = []
    previous: SadeghiSteadyState | None = None
    for detuning in np.asarray(tuple(detunings_mev), dtype=float):
        state = solve_steady_state(
            adapter,
            detuning_mev=float(detuning),
            distance_nm=distance_nm,
            intensity_w_cm2=intensity_w_cm2,
            response=response,
            initial_state=previous,
        )
        states.append(state)
        previous = state
    return states


def validate_detuning_grid_resolution(
    detunings_mev: Iterable[float],
    profile: Sadeghi2009Profile,
    *,
    max_step_fraction_of_gamma2: float = MAX_DETUNING_STEP_FRACTION_OF_GAMMA2,
) -> float:
    """Reject a publication grid that cannot resolve the bare QD linewidth.

    Strong driving can power-broaden a particular curve, but the same sweep
    also contains the weakly coupled/far-distance limit.  We therefore keep
    the conservative project-wide criterion ``dE <= hbar*Gamma2/4`` instead
    of silently relying on power broadening.
    """

    detunings = np.asarray(tuple(detunings_mev), dtype=float)
    if detunings.ndim != 1 or detunings.size < 2:
        raise ValueError("A detuning grid needs at least two points.")
    if np.any(~np.isfinite(detunings)) or np.any(np.diff(detunings) <= 0.0):
        raise ValueError("The detuning grid must be finite and strictly increasing.")
    if (
        not np.isfinite(max_step_fraction_of_gamma2)
        or max_step_fraction_of_gamma2 <= 0.0
    ):
        raise ValueError("max_step_fraction_of_gamma2 must be finite and positive.")
    maximum_step = float(np.max(np.diff(detunings)))
    gamma2_mev = profile.coherence_decay_ns_inv / MEV_TO_NS_INV
    allowed_step = max_step_fraction_of_gamma2 * gamma2_mev
    tolerance = 1.0e-12 * max(allowed_step, 1.0e-12)
    if maximum_step > allowed_step + tolerance:
        raise ValueError(
            "The Sadeghi detuning grid under-resolves the QD coherence width: "
            f"max step={maximum_step:.6g} meV, allowed<={allowed_step:.6g} meV "
            f"(Gamma2={gamma2_mev:.6g} meV). Increase the number of points."
        )
    return maximum_step


def logistic_switch_envelope(
    time_ns: float | np.ndarray,
    *,
    center_ns: float,
    rise_10_90_ns: float,
) -> np.ndarray:
    """Amplitude ramp whose 10--90 percent interval is exactly specified."""

    if rise_10_90_ns <= 0.0:
        raise ValueError("rise_10_90_ns must be positive.")
    slope = 2.0 * np.log(9.0) / rise_10_90_ns
    argument = np.clip(slope * (np.asarray(time_ns) - center_ns), -700.0, 700.0)
    return 1.0 / (1.0 + np.exp(-argument))


@dataclass(frozen=True)
class SadeghiTimeTrace:
    time_ns: np.ndarray
    distance_nm: float
    detuning_mev: float
    intensity_w_cm2: float
    excited_population: np.ndarray
    coherence_21: np.ndarray
    normalized_rabi_ns_inv: np.ndarray
    physical_excitation_ns_inv: np.ndarray
    literal_paper_G_ns_inv: np.ndarray
    negated_physical_excitation_ns_inv: np.ndarray
    drive_envelope: np.ndarray
    max_bloch_radius: float
    min_density_eigenvalue: float
    solver_success: bool
    nfev: int


def solve_switch_on_trace(
    adapter: SadeghiRWAAdapter,
    *,
    distance_nm: float,
    detuning_mev: float,
    intensity_w_cm2: float | None = None,
    response: MNPResponse = "modal",
    points: int = 2251,
    rtol: float = 2.0e-9,
    atol: float = 2.0e-11,
) -> SadeghiTimeTrace:
    """Integrate the physical RWA density matrix during the assumed ramp."""

    if points < 3:
        raise ValueError("points must be at least 3.")
    profile = adapter.profile
    intensity = (
        profile.strong_intensity_w_cm2
        if intensity_w_cm2 is None
        else float(intensity_w_cm2)
    )
    laser_energy_ev = profile.transition_energy_ev - detuning_mev * 1.0e-3
    coupling = adapter.coupling(
        laser_energy_ev=laser_energy_ev,
        distance_nm=distance_nm,
        response=response,
    )
    omega0_max = profile.isolated_rabi_ns_inv(intensity)
    detuning_ns_inv = detuning_mev * MEV_TO_NS_INV

    def rhs(time_ns: float, vector: np.ndarray) -> np.ndarray:
        population, coherence_real, coherence_imag = vector
        coherence = complex(coherence_real, coherence_imag)
        envelope = float(
            logistic_switch_envelope(
                time_ns,
                center_ns=profile.switch_center_ns,
                rise_10_90_ns=profile.switch_rise_10_90_ns,
            )
        )
        omega = (
            omega0_max * envelope * coupling.direct_factor
            + coupling.feedback_ns_inv * coherence
        )
        population_dot = (
            2.0 * np.imag(np.conj(omega) * coherence)
            - profile.population_decay_ns_inv * population
        )
        coherence_dot = (
            -(profile.coherence_decay_ns_inv + 1j * detuning_ns_inv)
            * coherence
            + 1j * omega * (1.0 - 2.0 * population)
        )
        return np.asarray(
            [population_dot, coherence_dot.real, coherence_dot.imag],
            dtype=float,
        )

    times = np.linspace(profile.time_start_ns, profile.time_end_ns, points)
    maximum_rate = max(
        abs(detuning_ns_inv),
        omega0_max * abs(coupling.direct_factor),
        abs(coupling.feedback_ns_inv),
        profile.coherence_decay_ns_inv,
        1.0,
    )
    max_step = min(0.005, 0.12 / maximum_rate)
    solution = solve_ivp(
        rhs,
        (profile.time_start_ns, profile.time_end_ns),
        np.asarray([0.0, 0.0, 0.0]),
        t_eval=times,
        method="DOP853",
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )
    if not solution.success or solution.t.size != times.size:
        raise RuntimeError(f"Sadeghi time integration failed: {solution.message}")
    population = np.asarray(solution.y[0], dtype=float)
    coherence = np.asarray(solution.y[1] + 1j * solution.y[2], dtype=complex)
    envelope = logistic_switch_envelope(
        times,
        center_ns=profile.switch_center_ns,
        rise_10_90_ns=profile.switch_rise_10_90_ns,
    )
    omega = (
        omega0_max * envelope * coupling.direct_factor
        + coupling.feedback_ns_inv * coherence
    )
    excitation = 2.0 * np.imag(np.conj(omega) * coherence)
    bloch_radius = np.sqrt(
        (1.0 - 2.0 * population) ** 2 + 4.0 * np.abs(coherence) ** 2
    )
    minimum_eigenvalue = 0.5 * (1.0 - bloch_radius)
    if np.max(bloch_radius) > 1.0 + 2.0e-6:
        raise RuntimeError(
            "The time-dependent density matrix lost positivity: "
            f"max Bloch radius={np.max(bloch_radius):.9g}."
        )
    return SadeghiTimeTrace(
        time_ns=times,
        distance_nm=float(distance_nm),
        detuning_mev=float(detuning_mev),
        intensity_w_cm2=intensity,
        excited_population=population,
        coherence_21=coherence,
        normalized_rabi_ns_inv=np.asarray(omega, dtype=complex),
        physical_excitation_ns_inv=np.asarray(excitation, dtype=float),
        literal_paper_G_ns_inv=np.asarray(
            -2.0 * np.imag(omega * coherence),
            dtype=float,
        ),
        negated_physical_excitation_ns_inv=np.asarray(-excitation, dtype=float),
        drive_envelope=np.asarray(envelope, dtype=float),
        max_bloch_radius=float(np.max(bloch_radius)),
        min_density_eigenvalue=float(np.min(minimum_eigenvalue)),
        solver_success=True,
        nfev=int(solution.nfev),
    )


def _write_csv(path: Path, fieldnames: list[str], rows: Iterable[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _pdf_sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _default_run_dir() -> Path:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return Path("results") / "sadeghi2009_comparison" / stamp


def run_comparison(
    *,
    output_dir: str | Path | None = None,
    response: MNPResponse = "modal",
    refit: bool = False,
    weak_points: int = 1001,
    strong_points: int = 5001,
    time_points: int = 2251,
    make_plots: bool = True,
) -> Path:
    """Calculate article-analogue Figures 2--7 and save auditable artifacts."""

    if weak_points < 5 or strong_points < 5 or time_points < 5:
        raise ValueError("All comparison grids must contain at least five points.")
    profile = Sadeghi2009Profile()
    weak_detunings = np.linspace(-0.2, 0.2, weak_points)
    strong_detunings = np.linspace(-1.0, 1.0, strong_points)
    weak_step_mev = validate_detuning_grid_resolution(weak_detunings, profile)
    strong_step_mev = validate_detuning_grid_resolution(strong_detunings, profile)
    # Only after all cheap resolution gates pass may a directory be created or
    # the potentially expensive modal refit be started.
    run_dir = Path(output_dir) if output_dir is not None else _default_run_dir()
    run_dir.mkdir(parents=True, exist_ok=True)
    adapter = build_sadeghi_adapter(profile, refit=refit)
    weak_states: dict[float, list[SadeghiSteadyState]] = {}
    strong_states: dict[float, list[SadeghiSteadyState]] = {}
    for distance in profile.distances_nm:
        weak_states[distance] = solve_steady_sweep(
            adapter,
            weak_detunings,
            distance_nm=distance,
            intensity_w_cm2=profile.weak_intensity_w_cm2,
            response=response,
        )
        strong_states[distance] = solve_steady_sweep(
            adapter,
            strong_detunings,
            distance_nm=distance,
            intensity_w_cm2=profile.strong_intensity_w_cm2,
            response=response,
        )

    steady_rows: list[dict[str, object]] = []
    for regime, collection in (("weak", weak_states), ("strong", strong_states)):
        for distance, states in collection.items():
            for state in states:
                steady_rows.append(
                    {
                        "regime": regime,
                        "distance_nm": distance,
                        "detuning_mev": state.detuning_mev,
                        "laser_energy_ev": state.laser_energy_ev,
                        "excited_population": state.excited_population,
                        "coherence_21_real": state.coherence_21.real,
                        "coherence_21_imag": state.coherence_21.imag,
                        "normalized_rabi_real_ns_inv": state.normalized_rabi_ns_inv.real,
                        "normalized_rabi_imag_ns_inv": state.normalized_rabi_ns_inv.imag,
                        "physical_excitation_ns_inv": state.physical_excitation_ns_inv,
                        "literal_paper_G_ns_inv": state.literal_paper_G_ns_inv,
                        "negated_physical_excitation_ns_inv": (
                            state.negated_physical_excitation_ns_inv
                        ),
                        "bloch_radius": state.bloch_radius,
                        "residual_norm": state.residual_norm,
                        "max_jacobian_real_part_ns_inv": (
                            state.max_jacobian_real_part_ns_inv
                        ),
                        "locally_stable": state.locally_stable,
                    }
                )
    _write_csv(
        run_dir / "figures_2_3_4_steady_state.csv",
        list(steady_rows[0]),
        steady_rows,
    )

    time_traces: dict[tuple[float, float], SadeghiTimeTrace] = {}
    for detuning in (0.0, 0.3, -0.3):
        for distance in (100.0, 15.0):
            time_traces[(detuning, distance)] = solve_switch_on_trace(
                adapter,
                distance_nm=distance,
                detuning_mev=detuning,
                response=response,
                points=time_points,
            )
    time_rows: list[dict[str, object]] = []
    for (detuning, distance), trace in time_traces.items():
        for index, time_ns in enumerate(trace.time_ns):
            time_rows.append(
                {
                    "detuning_mev": detuning,
                    "distance_nm": distance,
                    "time_ns": time_ns,
                    "drive_envelope": trace.drive_envelope[index],
                    "excited_population": trace.excited_population[index],
                    "coherence_21_real": trace.coherence_21[index].real,
                    "coherence_21_imag": trace.coherence_21[index].imag,
                    "normalized_rabi_real_ns_inv": trace.normalized_rabi_ns_inv[index].real,
                    "normalized_rabi_imag_ns_inv": trace.normalized_rabi_ns_inv[index].imag,
                    "physical_excitation_ns_inv": trace.physical_excitation_ns_inv[index],
                    "literal_paper_G_ns_inv": trace.literal_paper_G_ns_inv[index],
                    "negated_physical_excitation_ns_inv": (
                        trace.negated_physical_excitation_ns_inv[index]
                    ),
                }
            )
    _write_csv(
        run_dir / "figures_5_6_7_switch_on.csv",
        list(time_rows[0]),
        time_rows,
    )

    carrier_material = complex(
        adapter.alpha_physical_au(profile.transition_energy_ev, response="material")
    )
    carrier_modal = complex(
        adapter.alpha_physical_au(profile.transition_energy_ev, response="modal")
    )
    metadata = {
        "comparison": "Sadeghi 2009 using the unchanged native QD-MNP model",
        "article": {
            "title": (
                "The inhibition of optical excitations and enhancement of Rabi "
                "flopping in hybrid quantum dot-metallic nanoparticle systems"
            ),
            "doi": "10.1088/0957-4484/20/22/225401",
            "local_pdf": "articles/sadeghi2009.pdf",
            "local_pdf_sha256": _pdf_sha256(Path("articles/sadeghi2009.pdf")),
        },
        "response_used": response,
        "mathematical_core_modified": False,
        "numerical_settings": {
            "response": response,
            "refit_modal_fit": refit,
            "weak_points": weak_points,
            "weak_detuning_interval_mev": [-0.2, 0.2],
            "strong_points": strong_points,
            "strong_detuning_interval_mev": [-1.0, 1.0],
            "time_points": time_points,
            "make_plots": make_plots,
        },
        "rwa_adapter_reason": (
            "The paper itself uses RWA and nanosecond dynamics; the native passive "
            "modal alpha is evaluated adiabatically at the optical carrier."
        ),
        "sign_audit": {
            "coherence_convention": (
                "rho_21 from the paper; Omega_script=-Omega_paper"
            ),
            "physical_population_pump": "2 Im(conj(Omega_script) rho_21)",
            "literal_paper_column": (
                "literal_paper_G_ns_inv = -2 Im(Omega_script rho_21)"
            ),
            "diagnostic_negation_column": (
                "negated_physical_excitation_ns_inv = -physical"
            ),
            "reason": (
                "Equations (4) and (5) of the paper otherwise drive an isolated "
                "ground-state QD to negative population; its plotted G is negative."
            ),
        },
        "profile_provenance": profile.provenance(),
        "physical_parameters": params_to_physical_dict(
            adapter.params,
            orientation="long",
        ),
        "derived": {
            "gamma1_ns_inv": profile.population_decay_ns_inv,
            "Gamma2_ns_inv": profile.coherence_decay_ns_inv,
            "pure_dephasing_ns_inv": profile.pure_dephasing_ns_inv,
            "local_field_factor": profile.qd_local_field_factor,
            "weak_isolated_rabi_ns_inv": profile.isolated_rabi_ns_inv(
                profile.weak_intensity_w_cm2
            ),
            "strong_isolated_rabi_ns_inv": profile.isolated_rabi_ns_inv(
                profile.strong_intensity_w_cm2
            ),
            "surface_gaps_nm": {
                str(distance): profile.surface_gap_nm(distance)
                for distance in profile.distances_nm
            },
            "weak_detuning_step_mev": weak_step_mev,
            "strong_detuning_step_mev": strong_step_mev,
            "detuning_step_limit_mev": (
                MAX_DETUNING_STEP_FRACTION_OF_GAMMA2
                * profile.coherence_decay_ns_inv
                / MEV_TO_NS_INV
            ),
        },
        "modal_fit": {
            "n_modes": int(adapter.fit.strengths_au2.size),
            "fit_window_ev": list(adapter.fit_window_ev),
            "alpha_inf": adapter.fit.alpha_inf,
            "strengths_nonnegative": bool(
                np.all(adapter.fit.strengths_au2 >= 0.0)
            ),
            "passive_for_all_positive_frequencies": bool(
                adapter.fit.passive_for_all_positive_frequencies
            ),
            "passive_on_fit_window": bool(adapter.fit.passive_on_fit_window),
            "rms_alpha": adapter.fit.rms_alpha,
            "rms_inverse_alpha": adapter.fit.rms_inv_alpha,
            "fit_objective_score": adapter.fit.cost,
            "normalized_rms_alpha": adapter.fit.normalized_rms_alpha,
            "normalized_rms_inv_alpha": adapter.fit.normalized_rms_inv_alpha,
            "max_normalized_alpha_error": adapter.fit.max_normalized_alpha_error,
            "sampled_minimum_imaginary_alpha_fit_window": (
                adapter.fit.min_imag_alpha_fit_window
            ),
            "passivity_grid_points": adapter.fit.passivity_grid_points,
            "carrier_relative_error": float(
                abs(carrier_modal - carrier_material) / abs(carrier_material)
            ),
        },
        "time_solver": {
            "ramp": "logistic amplitude",
            "center_ns": profile.switch_center_ns,
            "rise_10_90_ns": profile.switch_rise_10_90_ns,
            "time_interval_ns": [profile.time_start_ns, profile.time_end_ns],
            "maximum_bloch_radius": max(
                trace.max_bloch_radius for trace in time_traces.values()
            ),
            "minimum_density_eigenvalue": min(
                trace.min_density_eigenvalue for trace in time_traces.values()
            ),
        },
        "steady_state_stability": {
            "exported_fixed_point_count": len(steady_rows),
            "all_exported_fixed_points_locally_stable": all(
                bool(row["locally_stable"]) for row in steady_rows
            ),
            "maximum_jacobian_real_part_ns_inv": max(
                float(row["max_jacobian_real_part_ns_inv"])
                for row in steady_rows
            ),
            "criterion": "max Re(eigenvalue(J)) < 0",
        },
        "limitations": [
            "Sadeghi does not print a, eps_h, eps_QD, transition energy, QD radius, or metal table.",
            "The reconstructed source used Palik Au, while the project uses Johnson-Christy.",
            "The exact switch-on function is not specified in the article.",
            (
                "At R=100 nm and Delta=+/-0.3 meV the printed parameters give "
                "rho22 about 0.005, whereas Figure 7 is of order 0.2; a detuning "
                "near 0.03--0.04 meV would be required. This approximate tenfold "
                "scale discrepancy is internal to the article and is not repaired "
                "by a hidden rescaling."
            ),
            "At R=15 nm, a/R=0.5; higher MNP multipoles can be important.",
            "The QD is treated as a point because its radius is not given.",
            "Distance-dependent spontaneous/Purcell decay is not calculated by this electrostatic model.",
        ],
    }
    with (run_dir / "metadata.json").open("w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)

    # Avoid stale optional plots when an explicit output directory is reused
    # with --no-plots.  Only exact filenames owned by this script are touched.
    for plot_name in _SADEGHI_PLOT_ARTIFACTS:
        (run_dir / plot_name).unlink(missing_ok=True)
    if make_plots:
        colors = {100.0: "C0", 20.0: "C1", 17.0: "C2", 15.0: "C3"}

        fig, ax = plt.subplots(figsize=(7.2, 4.6))
        for distance, states in weak_states.items():
            ax.plot(
                [state.detuning_mev for state in states],
                [state.excited_population for state in states],
                label=f"R={distance:g} nm",
                color=colors[distance],
            )
        ax.set(xlabel=r"$\Delta_{12}$ (meV)", ylabel=r"$\rho_{22}$")
        ax.set_title("Sadeghi Fig. 2 analogue: weak-field population")
        ax.legend()
        ax.grid(alpha=0.25)
        fig.tight_layout()
        fig.savefig(run_dir / "figure_2_population.png", dpi=180)
        plt.close(fig)

        for figure_number, collection, title in (
            (3, weak_states, "weak field"),
            (4, strong_states, "strong field"),
        ):
            fig, axes = plt.subplots(3, 1, figsize=(7.2, 8.5), sharex=True)
            for distance, states in collection.items():
                detuning = [state.detuning_mev for state in states]
                axes[0].plot(
                    detuning,
                    [state.normalized_rabi_ns_inv.real for state in states],
                    label=f"R={distance:g} nm",
                    color=colors[distance],
                )
                axes[1].plot(
                    detuning,
                    [state.normalized_rabi_ns_inv.imag for state in states],
                    color=colors[distance],
                )
                axes[2].plot(
                    detuning,
                    [state.literal_paper_G_ns_inv for state in states],
                    color=colors[distance],
                )
            axes[0].set_ylabel(r"Re $\Omega_{\rm script}$ (ns$^{-1}$)")
            axes[1].set_ylabel(r"Im $\Omega_{\rm script}$ (ns$^{-1}$)")
            axes[2].set_ylabel(r"literal paper $G$ (ns$^{-1}$)")
            axes[2].set_xlabel(r"$\Delta_{12}$ (meV)")
            axes[0].legend(ncol=2)
            for ax in axes:
                ax.grid(alpha=0.25)
            fig.suptitle(f"Sadeghi Fig. {figure_number} analogue: {title}")
            fig.tight_layout()
            fig.savefig(run_dir / f"figure_{figure_number}_rabi_and_rate.png", dpi=180)
            plt.close(fig)

        fig, axes = plt.subplots(3, 1, figsize=(7.2, 8.5), sharex=True)
        for distance in (100.0, 15.0):
            trace = time_traces[(0.0, distance)]
            label = f"R={distance:g} nm"
            axes[0].plot(trace.time_ns, trace.normalized_rabi_ns_inv.real, label=label)
            axes[1].plot(trace.time_ns, trace.normalized_rabi_ns_inv.imag)
            axes[2].plot(trace.time_ns, trace.literal_paper_G_ns_inv)
        axes[0].set_ylabel(r"Re $\Omega_{\rm script}$ (ns$^{-1}$)")
        axes[1].set_ylabel(r"Im $\Omega_{\rm script}$ (ns$^{-1}$)")
        axes[2].set_ylabel(r"literal paper $G$ (ns$^{-1}$)")
        axes[2].set_xlabel("time (ns)")
        axes[0].legend()
        for ax in axes:
            ax.grid(alpha=0.25)
        fig.suptitle("Sadeghi Fig. 5 analogue: resonant switch-on")
        fig.tight_layout()
        fig.savefig(run_dir / "figure_5_switch_on_rabi_and_rate.png", dpi=180)
        plt.close(fig)

        fig, ax = plt.subplots(figsize=(7.2, 4.6))
        for distance in (100.0, 15.0):
            trace = time_traces[(0.0, distance)]
            ax.plot(trace.time_ns, trace.excited_population, label=f"R={distance:g} nm")
        ax.plot(
            time_traces[(0.0, 100.0)].time_ns,
            0.5 * time_traces[(0.0, 100.0)].drive_envelope,
            ":",
            color="0.4",
            label="0.5 x drive envelope",
        )
        ax.set(xlabel="time (ns)", ylabel=r"$\rho_{22}$")
        ax.set_title("Sadeghi Fig. 6 analogue: resonant Rabi flopping")
        ax.legend()
        ax.grid(alpha=0.25)
        fig.tight_layout()
        fig.savefig(run_dir / "figure_6_resonant_population.png", dpi=180)
        plt.close(fig)

        fig, axes = plt.subplots(2, 1, figsize=(7.2, 6.8), sharex=True)
        for ax, detuning in zip(axes, (0.3, -0.3)):
            for distance in (100.0, 15.0):
                trace = time_traces[(detuning, distance)]
                ax.plot(
                    trace.time_ns,
                    trace.excited_population,
                    label=f"R={distance:g} nm",
                )
            ax.set_ylabel(r"$\rho_{22}$")
            ax.set_title(rf"$\Delta_{{12}}={detuning:+.1f}$ meV")
            ax.grid(alpha=0.25)
        axes[0].legend()
        axes[1].set_xlabel("time (ns)")
        fig.suptitle("Sadeghi Fig. 7 analogue: detuned population")
        fig.tight_layout()
        fig.savefig(run_dir / "figure_7_detuned_population.png", dpi=180)
        plt.close(fig)

    return run_dir


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Calculate Sadeghi-2009 figure analogues with the unchanged native "
            "quasistatic QD-MNP model."
        )
    )
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--response", choices=("modal", "material"), default="modal")
    parser.add_argument(
        "--refit",
        action="store_true",
        help="Regenerate the cached passive N=9 fit through the current core fitter.",
    )
    parser.add_argument("--weak-points", type=int, default=1001)
    parser.add_argument("--strong-points", type=int, default=5001)
    parser.add_argument("--time-points", type=int, default=2251)
    parser.add_argument("--no-plots", action="store_true")
    return parser


def main() -> None:
    args = _build_parser().parse_args()
    run_dir = run_comparison(
        output_dir=args.output_dir,
        response=args.response,
        refit=args.refit,
        weak_points=args.weak_points,
        strong_points=args.strong_points,
        time_points=args.time_points,
        make_plots=not args.no_plots,
    )
    print(f"Saved Sadeghi-2009 comparison to {run_dir}")


if __name__ == "__main__":
    main()
