"""Recalculate S1 from a recorded article command into a separate directory.

Preserve the original manifest, data and failure logs. The new receipt records
the source change; this is a standalone S1 calculation, not a full-run resume.
"""

from qdmnp.pipeline import ROOT, Tee, material_fit_cache, sha, write_json

import argparse
from contextlib import redirect_stderr, redirect_stdout
from datetime import datetime, timezone
import json
from pathlib import Path
import sys
import time

from qdmnp.observables import calculate_work_loss_spectrum_material_comparison as calculator
from qdmnp.observables.plot_work_loss_spectrum_material_comparison import (
    plot_work_loss_spectrum_material_comparison,
)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_directory", type=Path)
    parser.add_argument("--output", type=Path, required=True, help="New output directory.")
    args = parser.parse_args(argv)
    origin = args.run_directory.resolve()
    destination = args.output.resolve()
    manifest_path = origin / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    records = [v for k, v in manifest["steps"].items() if k.startswith("supp01_work_spectrum:")]
    if not records:
        parser.error("The manifest has no recorded S1 command.")
    command = records[-1]["command"]
    if command[1:3] != ["-m", calculator.__name__]:
        parser.error("Unexpected S1 calculator in the recorded command.")
    output = destination / "supp01_work_spectrum.npz"
    arguments = list(command[3:])
    arguments[arguments.index("--output") + 1] = str(output)
    parsed = calculator.parse_args(arguments)
    source = parsed.selection_source_artifact.resolve()
    source_record = next((r for r in manifest["steps"].values()
                          if r.get("status") == "complete"
                          and Path(r["output"]).resolve() == source), None)
    if source_record is None or not source.exists() or sha(source) != source_record["sha256"]:
        parser.error("The S1 fluence-selection artifact is missing or differs from the manifest.")
    # Never reinterpret the original results as generated by the repaired code.
    destination.mkdir(parents=True, exist_ok=False)
    changes = {}
    for name, old_hash in manifest["identity"]["source_sha256"].items():
        current = ROOT / name
        current_hash = sha(current) if current.exists() else None
        if current_hash != old_hash:
            changes[name] = {"original": old_hash, "current": current_hash}
    receipt = {
        "scope": "S1 only; original full-run status and validation verdict unchanged",
        "status": "running", "started_utc": datetime.now(timezone.utc).isoformat(),
        "original_manifest": {"path": str(manifest_path), "sha256": sha(manifest_path)},
        "selection_artifact": {"path": str(source), "sha256": sha(source)},
        "source_changes_since_original_run": changes,
        "rerun_script_sha256": sha(Path(__file__)),
        "original_command": command,
        "calculation_command": [sys.executable, "-m", calculator.__name__, *arguments],
        "material_fit_cache": str(origin / "material_fit_cache"),
    }
    receipt_path = destination / "rerun_receipt.json"
    write_json(receipt_path, receipt)
    start = time.perf_counter()
    try:
        with (destination / "calculation.log").open("w", encoding="utf-8") as log:
            with redirect_stdout(Tee(sys.stdout, log)), redirect_stderr(Tee(sys.stderr, log)):
                with material_fit_cache(origin / "material_fit_cache"):
                    calculator.main(arguments)
                figure = plot_work_loss_spectrum_material_comparison(
                    output, destination / "supp01.png"
                )
        receipt.update(status="complete", artifacts={
            str(p): sha(p) for p in (output, figure)
        })
    except Exception as exc:
        receipt.update(status="failed", error=f"{type(exc).__name__}: {exc}")
        raise
    finally:
        receipt["elapsed_s"] = time.perf_counter() - start
        write_json(receipt_path, receipt)
    print(f"S1 data, figure and provenance: {destination}")


if __name__ == "__main__":
    main()
